/* Copyright 2026 dvbipitools authors. Licensed under GPL-3.0-or-later.
 * See NOTICE and LICENSE for details and authorship information. */

#include <stdio.h>

#include "priv.h"
#include "../version.h"

void rdh_print_help(void) {
  printf(
  "usage: %s -i <uri> [--sid <n>] [--sdt <name>] [-i <uri> ...] {-m <mcast>:<port>|-R <uri>} [options]\n\n"
  "fetch one or more icecast/shoutcast streams and re-mux them as one DVB-IPI multicast\n"
  "(a single -i: normal SPTS. multiple -i: MPTS, one program per input)\n\n"
  "options:\n"
  "  -i, --input <uri>              icecast/shoutcast source, http:// or https://. repeatable\n"
  "  -m, --mcast <g>:<p>            output multicast group:port ([addr6]:port for v6)\n"
  "  -O, --out-iface <iface>        outgoing multicast interface\n"
  "  -r, --rtp                      output in RTP (default: plain UDP; -m output only)\n"
  "  -T, --ttl <n>                  multicast TTL (default: 1)\n"
  "      --dscp <v>                 output DSCP: video-high|video-low|voice|\n"
  "                                 signalling|best-effort|0..63 (default: video-high)\n"
  "      --al-fec <L>:<D>           Annex E Layer 1 FEC (SMPTE 2022-1), L*D<=400, L<=40\n"
  "      --al-fec-port <port>       AL-FEC stream UDP port, requires --al-fec\n"
  "  -n, --nit <text>               NIT network_name\n"
  "      --default-provider <p>     SDT default provider name, if not overridden\n"
  "                                 by --provider at programme level (default: " TOOL_NAME ")\n"
  "  -R, --remote <uri>             rist://host:port[?query] or srt://host:port output,\n"
  "                                 bonded with any other -R of the same scheme given\n"
  "                                 (requires librist/libsrt respectively; a single -R set\n"
  "                                 is one scheme at a time, rist:// and srt:// don't mix)\n"
  "      --rist-profile <p>         simple|main -R rist:// peers only (default: simple)\n"
  "      --rist-secret <psk>        -R rist:// pre-shared key (requires --rist-profile main)\n"
  "      --rist-encryption-type <b> AES key size 128|256 (--rist-profile main)\n"
  "      --rist-cname <name>        -R rist:// cname (default: library default)\n"
  "      --rist-buffer <ms>         -R rist:// recovery buffer (default: library default)\n"
  "      --srt-group-mode <m>       broadcast|backup required when bonding >1 -R srt:// peer\n"
  "      --srt-passphrase <pw>      passphrase for every -R srt:// peer, 10..79 chars\n"
  "      --srt-pbkeylen <n>         AES key length for --srt-passphrase: 16|24|32\n"
  "      --srt-streamid <id>        SRTO_STREAMID for every -R srt:// peer\n"
  "      --srt-packetfilter <c>     SRTO_PACKETFILTER for every -R srt:// peer\n"
  "      --srt-latency <ms>         SRTO_LATENCY for every -R srt:// peer\n"
  "  -e, --error <seconds>          on input error, reconnect after N s (default: fail once,\n"
  "                                 always retries when more than one -i is given)\n"
  "  -k, --insecure                 skip TLS verification\n"
  "      --tsid <n>                 transport_stream_id (default 1)\n"
  "      --onid <n>                 original_network_id (default 1)\n"
  "  -v, --verbose                  periodic stats on stderr\n"
  "      --color <when>             auto|always|never (default auto)\n"
  "      --metrics <path>           socket for metrics (default: /run/dvbipitools/metrics.sock)\n"
  "      --metrics-id <name>        stable instance id; metrics disabled unless set\n"
  "      --metrics-interval <s>     snapshot interval in seconds (default: 5)\n"
  "      --metrics-inspect-ts <lvl> TS health metrics: off|basic|medium|full (default: off)\n"
  "      --metrics-inspect-ts-pids <list> per pid and per service counters (default: none)\n"
  "      --cas-algo <a>             enable CAS: cissa|csa2|csa1 (default: disabled)\n"
  "      --cas-ecmg <ep>            ECMG address, tcp://host:port; repeatable, one CAS vendor\n"
  "                                 per --cas-ecmg (required with --cas-algo)\n"
  "      --cas-cp-duration <ms>     crypto-period duration in ms, shared by every vendor (default: 10000)\n"
  "      --cas-fallback-clear       on total outage (or a --cas-required vendor down): clear\n"
  "                                 instead of staying scrambled on the last known-good CW\n"
  "      --biss2-sw <hex32>         enable BISS2 Mode 1/E: 32 hex char Session Word, scrambles\n"
  "                                 with CISSA. No ECMG/EMMG. Mutually exclusive with --cas-algo\n"
  "      --biss2-emit-esw <id>      with --biss2-sw: log the AES-128-ECB Encrypted Session Word\n"
  "                                 for this 32 hex char receiver ID, for out-of-band distribution\n"
  "      --biss1-sw <hex12>         enable legacy BISS1 Mode 1: 12 hex char Session Word,\n"
  "                                 scrambles with CSA1. Mutually exclusive with --biss2-sw/--cas-algo\n"
  "      --biss2-ca-receivers <dir> enable BISS2 Mode CA: directory of PEM public key files\n"
  "                                 one per entitled receiver or group.\n"
  "                                 Mutually exclusive with --biss1-sw/--biss2-sw/--cas-algo\n"
  "      --biss2-ca-session-id <n>  unique entitlement_session_id, dec or 0x-hex, 16 bit\n"
  "                                 (default: random at startup)\n"
  "  -d, --daemonize                fork to background after startup\n"
  "  -c, --config <path>            YAML config file (default: %s, if present)\n"
  "      --config-strict            fail on config file issues instead of warnings\n"
  "      --configtest               check the config file, then exit\n"
  "  -h, --help                     this help\n\n"
  "scoped to the -i input right before:\n"
  "      --sid <n>                  service_id/program_number (default: auto)\n"
  "      --jitter-ms <ms>           de-jitter buffer, 1..10000 (default: off)\n"
  "  -s, --sdt <name>               SDT service_name (default: auto)\n"
  "      --provider <name>          SDT service_provider_name (default: " TOOL_NAME ")\n\n"
  "scoped to the --cas-ecmg right before:\n"
  "      --cas-ecmg-version <n>     protocol version 2|3 (default: autoneg)\n"
  "      --cas-super-id <n>         Super_CAS_id, dec or 0x-hex (per vendor)\n"
  "      --cas-ecm-id <n>           ECM_id (per vendor)\n"
  "      --cas-ecm-pid <pid>        output ECM PID (default: 0x0020)\n"
  "      --cas-emmg-port <n>        our EMMG listener port (default: 8002)\n"
  "      --cas-emmg-max-conns <n>   max concurrent EMMG clients (default: 8, max: 64)\n"
  "      --cas-emmg-version <n>     EMMG protocol 2|3 (default: client)\n"
  "      --cas-emmg-reverse <ep>    reverse EMMG, dial out to tcp://host:port\n"
  "      --cas-emm-pid <pid>        EMM output PID (default: 0x0021)\n"
  "      --cas-resilience <r>       ECMG loss frozen|cycling|silent (default: frozen)\n"
  "      --cas-required             outage forces global fallback regardless of others\n"
  "      --cas-cwenc-algo <a>       encrypt CW_provision's\n"
  "                                 CWs per Annex D, des56|aes128|aes256 (default: off)\n"
  "      --cas-cwenc-aes-mode <m>   stream|ecb, aes* only (default: stream)\n"
  "      --cas-cwenc-fixed-key <hx> 14/32/64 hex chars for des56/aes128/aes256 (default: Annex D ROM)\n"
  "      --cas-cwenc-key-list-a <p> 2048-byte Annex D key list file\n"
  "      --cas-cwenc-key-list-b <p> same, second list\n\n"
  "examples:\n"
  "  %s -i https://example.com/radio.m3u --sdt \"Channel 1\" -m 239.1.1.1:5000\n"
  "  %s -i http://example.com/somechannel/aac --sdt \"Some Channel\" -i https://example.com/radio.m3u --sdt \"Channel 1\" -m 239.1.1.2:5000 -r -e 5\n",
  TOOL_NAME, DEFAULT_CONFIG_PATH, TOOL_NAME, TOOL_NAME);
}
