/* Copyright 2026 dvbipitools authors. Licensed under GPL-3.0-or-later.
 * See NOTICE and LICENSE for details and authorship information. */

#include <stdio.h>

#include "priv.h"
#include "../version.h"

void rec_print_help(void) {
  printf(
  "usage: %s -i <uri> -o <target> [options]\n\n"
  "record or replay a transport stream from/to a file, SRT, RIST or stdin/out\n\n"
  "sources (-i):\n"
  "  rtp://@<group>:<port>        RTP wrapped TS multicast (@ optional)\n"
  "  udp://@<group>:<port>        raw TS multicast (@ optional)\n"
  "  rtp://<src>@<group>:<port>   source-specific multicast (SSM), same for udp://\n"
  "  http://<host>:<port>/<path>  HTTP TS stream\n"
  "  https://<host>:<port>/<path> same, TLS (--insecure skips verification)\n"
  "  -                            stdin, TS or RTP wrapped TS\n"
  "  <path>                       a file, TS or RTP wrapped TS\n"
  "  rist://@<host>:<port>[?q]    RIST receiver, single peer (@ required)\n"
  "  srt://[@]<host>:<port>       SRT receiver, single peer (@=listen, else call out)\n"
  "  IPv6 groups in brackets, e.g. rtp://@[ff3e::1]:8700\n\n"
  "outputs (-o, repeat for multiple destinations)\n"
  "  -                            stdout\n"
  "  rtp://@<group>:<port>        RTP wrapped multicast (-f raw|ts only)\n"
  "  udp://@<group>:<port>        raw multicast (-f raw|ts only)\n"
  "  rist://<host>:<port>[?q]     RIST sender, single peer (-f raw|ts only)\n"
  "  srt://<host>:<port>          SRT sender, single peer (-f raw|ts only)\n"
  "  rtmp(s)://<host>[:port]/<app>/<key>  RTMP(S) publish\n\n"
  "options:\n"
  "  -o, --out <target>             output, repeatable: file, \"-\" for stdout, or\n"
  "                                 rtp://udp://rist://srt://rtmp://rtmps://\n"
  "  -i, --in <uri>                 input source\n"
  "  -a, --audio <track>            audio track from 1, or \"all\" (default: all)\n"
  "  -f, --format <format>          raw|ts|mkv|mka|mp4|m4a (default: from -o suffix,\n"
  "                                 else ts; mkv/mka/mp4/m4a rejected with a network\n"
  "                                 -o, raw rejected on -o rtmp://rtmps://\n"
  "  -p, --pmt-pid <pid|all>        MPTS source only: pin one PMT pid, or record\n"
  "                                 every program (\"all\"; rejected with -f mkv/mp4).\n"
  "                                 fails on SPTS.\n"
  "  -s, --subtitles <mode>         strip|keep|srt. srt on mkv/mka/mp4/m4a only\n"
  "                                 (default: keep) - this \"srt\" means SubRip\n"
  "  -t, --time <duration>          e.g. 90, 5m, 5m30s, 1h3m20s, 01:20:03, 10:20\n"
  "  -I, --iface <iface>            interface name for -i's multicast join\n"
  "  -O, --out-iface <iface>        interface for -o rtp://udp://'s multicast send\n"
  "      --ttl <n>                  multicast TTL for -o rtp://udp:// (default: kernel, 1)\n"
  "      --al-fec <L>:<D>           Annex E Layer 1 FEC (SMPTE 2022-1), -i/-o rtp:// only,\n"
  "                                 L*D<=400, L<=40\n"
  "      --al-fec-port <port>       AL-FEC stream UDP port, requires --al-fec\n"
  "      --rist-profile <p>         simple|main. -o rist:// only (default: simple)\n"
  "      --rist-secret <psk>        -o rist:// pre-shared key. requires --rist-profile main\n"
  "      --rist-encryption-type <b> AES key size 128|256. outgoing (--rist-profile main)\n"
  "      --rist-cname <name>        -o rist:// cname (default: library default)\n"
  "      --rist-buffer <ms>         -o rist:// recovery buffer (default: library default)\n"
  "      --rist-profile-in <p>      simple|main; -i rist:// only (default: simple)\n"
  "      --rist-encryption-type-in <b> AES key size 128|256. input (--rist-profile-in main)\n"
  "      --srt-passphrase-in <pw>   passphrase for -i srt://, 10..79 chars\n"
  "      --srt-pbkeylen-in <n>      AES key length for --srt-passphrase-in: 16|24|32\n"
  "      --srt-streamid-in <id>     SRTO_STREAMID for -i srt://\n"
  "      --srt-packetfilter-in <c>  SRTO_PACKETFILTER for -i srt://\n"
  "      --srt-latency-in <ms>      SRTO_LATENCY for -i srt://\n"
  "      --srt-passphrase <pw>      passphrase for every -o srt:// target\n"
  "      --srt-pbkeylen <n>         AES key length for --srt-passphrase: 16|24|32\n"
  "      --srt-streamid <id>        SRTO_STREAMID for every -o srt:// target\n"
  "      --srt-packetfilter <c>     SRTO_PACKETFILTER for every -o srt:// target\n"
  "      --srt-latency <ms>         SRTO_LATENCY for every -o srt:// target\n"
  "      --insecure                 skip TLS verification at -o rtmps://\n"
  "  -v, --verbose                  periodic recording stats on stderr\n"
  "      --sub-lead <ms>            shift VT->SRT captions earlier (default 1000)\n"
  "      --color <when>             stdout colors: auto|always|never (default auto)\n"
  "      --metrics <path>           socket for metrics (default: /run/dvbipitools/metrics.sock)\n"
  "      --metrics-id <name>        stable instance id. metrics are disabled unless set\n"
  "      --metrics-interval <s>     snapshot interval in seconds (default: 5)\n"
  "      --metrics-inspect-ts <lvl> TS health metrics: off|basic|medium|full (default: off)\n"
  "      --metrics-inspect-ts-pids <list> per pid and per service counters (default: none)\n"
  "      --ret <addr>:<port>        RET/RAMS server unicast address (rtp:// only)\n"
  "      --no-ret-mc                skip joining the RET/RAMS multicast repair session\n"
  "      --ret-mc-port <port>       override the repair session port (default: -i's port)\n"
  "      --ret-pt <n>               RTX payload type, must match the RET server (default 99)\n"
  "      --ret-wait <ms>            NACK timeout (default 200)\n"
  "      --pace                     file/stdin source only: pace output to the input's own\n"
  "                                 timing (RTP timestamp if RTP-framed, else PCR)\n"
  "      --strip <list>             comma list of NUL,NIT,AIT,EIT,CAT,ECM,EMM,RST,TDT,TOT,INT\n"
  "                                 (-f ts only) or LCEVC to drop, or \"none\"\n"
  "                                 (default: NUL,NIT,AIT,EIT)\n"
  "  -c, --config <path>            YAML config file (default: %s, if present)\n"
  "      --config-strict            fail on config file issues instead of warnings\n"
  "      --configtest               check the config file, then exit\n"
  "  -h, --help                     this help\n\n"
  "formats:\n"
  "  raw   unwrap RTP only, transport stream otherwise untouched\n"
  "  ts    single program transport stream; drops stuffing, NIT, EIT,\n"
  "        AIT and CA/EMM, keeps SDT, rewrites PAT/PMT\n"
  "  mkv   video: H.264(AVC)/H.265(HEVC)/H.266(VVC)\n"
  "        audio: MP2/MP3/AC-3/E-AC-3/AAC/AAC-LATM/Opus/DTS/DTS-HD/DTS-HD-MA/TrueHD/AC-4\n"
  "  mka   same, audio only\n"
  "  mp4   video: H.264(AVC)/H.265(HEVC)/H.266(VVC)\n"
  "        audio: MP2/MP3/AC-3/E-AC-3/AAC/AAC-LATM/Opus/DTS/DTS-HD/DTS-HD-MA/TrueHD/AC-4\n\n"
  "  m4a   same, audio only\n\n"
  "examples:\n"
  "  %s -i rtp://@239.19.75.1:8700 -o show.ts\n"
  "  %s -i rtp://@239.19.75.1:8700 -o show.mkv -s srt -t 1h30m -v\n"
  "  %s -i udp://@239.0.175.1:8700 -o radio.mka -I eth0\n"
  "  %s -i http://10.0.0.1:4022/rtp/239.19.75.1:8700 -o show.ts\n"
  "  %s -i show.ts --pace -o rtp://@239.9.9.9:6000 -O eth1 --ttl 16\n"
  "  %s -i rtp://@239.19.75.1:8700 -o rtmp://live.example.com/app/key\n",
  TOOL_NAME, DEFAULT_CONFIG_PATH, TOOL_NAME, TOOL_NAME, TOOL_NAME, TOOL_NAME, TOOL_NAME, TOOL_NAME);
}
