/* Copyright 2026 dvbipitools authors. Licensed under GPL-3.0-or-later.
 * See NOTICE and LICENSE for details and authorship information. */

#include <stdio.h>

#include "priv.h"
#include "../version.h"

void srt_print_help(void) {
  printf(
    "usage: %s -i <uri> -o <uri> [options]\n\n"
    "bridge a DVB-IPI stream between plain RTP/UDP/file and an SRT link, either\n"
    "direction: exactly one of -i/-o must be srt://, the other a regular\n"
    "dipirec-style endpoint\n\n"
    "endpoints:\n"
    "  srt://<host>:<port>            SRT peer, calls out (caller)\n"
    "  srt://@<host>:<port>           SRT peer, binds/listens/accepts (listener)\n"
    "                                 repeat -i/-o to bond several links (--group-mode)\n"
    "                                 <host> is a numeric IP, not a hostname\n"
    "  rtp://@<group>:<port>          RTP wrapped SPTS multicast (@ optional)\n"
    "  udp://@<group>:<port>          raw SPTS multicast (@ optional)\n"
    "  http://<host>:<port>/<path>    HTTP TS stream, -i only\n"
    "  https://<host>:<port>/<path>   same, TLS (-k skips verification), -i only\n"
    "  -                              stdin (-i) or stdout (-o)\n"
    "  <path>                         a file\n"
    "  IPv6 addrs/groups in brackets, e.g. srt://@[::1]:9000, rtp://@[ff3e::1]:8700\n\n"
    "options:\n"
    "  -i, --in <uri>                 input (see above), repeatable if srt://\n"
    "  -o, --out <uri>                output (see above), repeatable if srt://\n"
    "  -I, --iface <iface>            interface for the non-SRT side's multicast join/send\n"
    "  -k, --insecure                 skip TLS verification, -i https:// only\n"
    "      --group-mode <mode>        broadcast|backup; required when bonding (repeated srt://)\n"
    "      --rendezvous               srt_rendezvous() instead of connect/listen; needs --local,\n"
    "                                 not combinable with @ or --group-mode\n"
    "      --local <host:port>        local bind address for --rendezvous\n"
    "      --passphrase <pw>          encryption passphrase, 10..79 chars\n"
    "      --pbkeylen <n>             16|24|32 (AES key length); default 16 if --passphrase set\n"
    "      --streamid <id>            SRTO_STREAMID, passed to a listening peer on accept\n"
    "      --packetfilter <cfg>       SRTO_PACKETFILTER config string, e.g. fec,cols:10,rows:5\n"
    "      --latency <ms>             SRTO_LATENCY; default library\n"
    "      --send-buffer-mult <n>     sender queue depth in latency windows, 1..32; default 4\n"
    "      --al-fec <L>:<D>           Annex E Layer 1 FEC (SMPTE 2022-1) on rtp:// L*D<=400, L<=40\n"
    "      --al-fec-port <port>       repair stream UDP port, requires --al-fec\n"
    "      --color <when>             auto|always|never (default auto)\n"
    "      --metrics <path>           socket for metrics (/run/dvbipitools/metrics.sock)\n"
    "      --metrics-id <name>        stable instance id; metrics disabled unless set\n"
    "      --metrics-interval <s>     snapshot interval in seconds (default: 5)\n"
    "      --metrics-inspect-ts <lvl> TS health metrics: off|basic|medium|full (default: off)\n"
    "  -v, --verbose                  periodic bridge stats on stderr\n"
    "  -d, --daemonize                fork to background after startup\n"
    "  -c, --config <path>            YAML config file (default: %s, if present)\n"
    "      --config-strict            fail on config file issues instead of warnings\n"
    "      --configtest               check the config file, then exit\n"
    "  -h, --help                     this help\n\n"
    "examples:\n"
    "  %s -i rtp://@239.1.1.1:5000 -o srt://1.2.3.4:9000 --latency 200\n"
    "  %s -i srt://@0.0.0.0:9000 -o rtp://@239.1.1.1:5000\n"
    "  %s -i rtp://@239.1.1.1:5000 -o srt://1.2.3.4:9000 -o srt://5.6.7.8:9000 --group-mode broadcast\n",
    TOOL_NAME, DEFAULT_CONFIG_PATH, TOOL_NAME, TOOL_NAME, TOOL_NAME);
}
