/* Copyright 2026 dvbipitools authors. Licensed under GPL-3.0-or-later.
 * See NOTICE and LICENSE for details and authorship information. */

#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "lib/ioutil.h"
#include "render.h"

typedef enum { M_GAUGE, M_COUNTER, M_INFO } metric_kind_t;

typedef struct {
  metrics_id_t id;
  const char *name;
  metric_kind_t kind;
  const char *help;
  const char *label_name;     /* NULL = no metric-specific label */
  int composite_input_reason; /* label on wire is "input" SEP "reason" */
} metric_def_t;

/* order matches protocol.h metric_id_t order, also render order */
static const metric_def_t DEFS[] = {
    {METRICS_ID_HEADEND_INFO, "dvbipi_headend_info", M_INFO, "toolkit build info", "version", 0},
    {METRICS_ID_METRICS_SNAPSHOTS_DROPPED_TOTAL, "dvbipi_metrics_snapshots_dropped_total", M_COUNTER, "snapshots this exporter failed to send", NULL, 0},
    {METRICS_ID_ERRORS_TOTAL, "dvbipi_errors_total", M_COUNTER, "network errors by reason", "reason", 0},
    {METRICS_ID_OUTPUT_PACKETS_TOTAL, "dvbipi_output_packets_total", M_COUNTER, "packets sent on the output", NULL, 0},
    {METRICS_ID_OUTPUT_BYTES_TOTAL, "dvbipi_output_bytes_total", M_COUNTER, "bytes sent on the output", NULL, 0},
    {METRICS_ID_OUTPUT_ERRORS_TOTAL, "dvbipi_output_errors_total", M_COUNTER, "output send errors", NULL, 0},
    {METRICS_ID_CONFIGURED_SERVICES, "dvbipi_configured_services", M_GAUGE, "services configured", NULL, 0},
    {METRICS_ID_ACTIVE_SERVICES, "dvbipi_active_services", M_GAUGE, "services currently active", NULL, 0},
    {METRICS_ID_INPUT_UP, "dvbipi_input_up", M_GAUGE, "1 if the input is currently connected", "input", 0},
    {METRICS_ID_INPUT_BYTES_TOTAL, "dvbipi_input_bytes_total", M_COUNTER, "bytes read from the input", "input", 0},
    {METRICS_ID_INPUT_RECONNECTS_TOTAL, "dvbipi_input_reconnects_total", M_COUNTER, "input reconnect count", "input", 0},
    {METRICS_ID_INPUT_ERRORS_TOTAL, "dvbipi_input_errors_total", M_COUNTER, "input errors by reason", NULL, 1},
    {METRICS_ID_INPUT_LAST_DATA_TIME_SECONDS, "dvbipi_input_last_data_time_seconds", M_GAUGE, "unix time of the last data received", "input", 0},
    {METRICS_ID_TS_PACKETS_TOTAL, "dvbipi_ts_packets_total", M_COUNTER, "transport stream packets processed", NULL, 0},
    {METRICS_ID_TS_CONTINUITY_ERRORS_TOTAL, "dvbipi_ts_continuity_errors_total", M_COUNTER, "continuity counter errors", NULL, 0},
    {METRICS_ID_TS_DISCONTINUITIES_TOTAL, "dvbipi_ts_discontinuities_total", M_COUNTER, "signaled discontinuities", NULL, 0},
    {METRICS_ID_TS_SYNC_ERRORS_TOTAL, "dvbipi_ts_sync_errors_total", M_COUNTER, "TS sync byte errors", NULL, 0},
    {METRICS_ID_PCR_DISCONTINUITIES_TOTAL, "dvbipi_pcr_discontinuities_total", M_COUNTER, "implausible PCR jumps", NULL, 0},
    {METRICS_ID_PSI_SECTIONS_TOTAL, "dvbipi_psi_sections_total", M_COUNTER, "PSI/SI sections generated by table", "table", 0},
    {METRICS_ID_PSI_ERRORS_TOTAL, "dvbipi_psi_errors_total", M_COUNTER, "PSI/SI section build errors by table", "table", 0},
    {METRICS_ID_CAS_ECMG_CONNECTED, "dvbipi_cas_ecmg_connected", M_GAUGE, "1 if connected to the ECMG", "cas", 0},
    {METRICS_ID_CAS_EMMG_CLIENTS, "dvbipi_cas_emmg_clients", M_GAUGE, "connected EMMG clients", "cas", 0},
    {METRICS_ID_CAS_CRYPTOPERIOD_TRANSITIONS_TOTAL, "dvbipi_cas_cryptoperiod_transitions_total", M_COUNTER, "cryptoperiod transitions", "cas", 0},
    {METRICS_ID_CAS_ECM_TOTAL, "dvbipi_cas_ecm_total", M_COUNTER, "ECMs generated", "cas", 0},
    {METRICS_ID_CAS_ECM_ERRORS_TOTAL, "dvbipi_cas_ecm_errors_total", M_COUNTER, "ECM generation errors", "cas", 0},
    {METRICS_ID_CAS_EMM_TOTAL, "dvbipi_cas_emm_total", M_COUNTER, "EMMs published", "cas", 0},
    {METRICS_ID_CAS_EMM_DROPPED_TOTAL, "dvbipi_cas_emm_dropped_total", M_COUNTER, "EMMs dropped, oversized or send queue full", "cas", 0},
    {METRICS_ID_CAS_SCRAMBLED_PACKETS_TOTAL, "dvbipi_cas_scrambled_packets_total", M_COUNTER, "packets scrambled", NULL, 0},
    {METRICS_ID_CAS_UNEXPECTED_CLEAR_PACKETS_TOTAL, "dvbipi_cas_unexpected_clear_packets_total", M_COUNTER, "clear packets on a managed pid before the ECMG was up", NULL, 0},
    {METRICS_ID_RADIO_AUDIO_FRAMES_TOTAL, "dvbipi_radio_audio_frames_total", M_COUNTER, "audio frames processed by codec", "codec", 0},
    {METRICS_ID_RADIO_AUDIO_FRAMING_ERRORS_TOTAL, "dvbipi_radio_audio_framing_errors_total", M_COUNTER, "audio framing/parse errors", NULL, 0},
    {METRICS_ID_RADIO_METADATA_UPDATES_TOTAL, "dvbipi_radio_metadata_updates_total", M_COUNTER, "metadata updates parsed", NULL, 0},
    {METRICS_ID_RADIO_METADATA_ERRORS_TOTAL, "dvbipi_radio_metadata_errors_total", M_COUNTER, "metadata parse errors", NULL, 0},
    {METRICS_ID_TV_SOURCE_PROGRAM_UP, "dvbipi_tv_source_program_up", M_GAUGE, "1 if the program has at least one active service", NULL, 0},
    {METRICS_ID_TV_SOURCE_PMT_UPDATES_TOTAL, "dvbipi_tv_source_pmt_updates_total", M_COUNTER, "PMT content changes seen", NULL, 0},
    {METRICS_ID_TV_SOURCE_PID_CHANGES_TOTAL, "dvbipi_tv_source_pid_changes_total", M_COUNTER, "elementary stream pid changes seen", NULL, 0},
    {METRICS_ID_TV_REMUX_PACKETS_TOTAL, "dvbipi_tv_remux_packets_total", M_COUNTER, "packets passed through the remux", NULL, 0},
    {METRICS_ID_TV_REMUX_DROPPED_PACKETS_TOTAL, "dvbipi_tv_remux_dropped_packets_total", M_COUNTER, "packets dropped by the remux", NULL, 0},
    {METRICS_ID_TV_AIT_SECTIONS_TOTAL, "dvbipi_tv_ait_sections_total", M_COUNTER, "AIT sections sent", NULL, 0},
    {METRICS_ID_TV_AIT_ERRORS_TOTAL, "dvbipi_tv_ait_errors_total", M_COUNTER, "AIT build errors", NULL, 0},
    {METRICS_ID_TV_EIT_QUEUE_DROPS_TOTAL, "dvbipi_tv_eit_queue_drops_total", M_COUNTER, "EIT sections discarded, reassembly queue full", NULL, 0},
    {METRICS_ID_SDS_SERVICE_PROVIDERS, "dvbipi_sds_service_providers", M_GAUGE, "service providers announced", NULL, 0},
    {METRICS_ID_SDS_SERVICES, "dvbipi_sds_services", M_GAUGE, "services announced", NULL, 0},
    {METRICS_ID_SDS_DOCUMENTS_GENERATED_TOTAL, "dvbipi_sds_documents_generated_total", M_COUNTER, "SD&S documents (re)generated", NULL, 0},
    {METRICS_ID_SDS_DOCUMENT_ERRORS_TOTAL, "dvbipi_sds_document_errors_total", M_COUNTER, "SD&S document generation errors", NULL, 0},
    {METRICS_ID_SDS_ANNOUNCEMENTS_TOTAL, "dvbipi_sds_announcements_total", M_COUNTER, "announcement cycles sent by transport", "transport", 0},
    {METRICS_ID_SDS_ANNOUNCEMENT_ERRORS_TOTAL, "dvbipi_sds_announcement_errors_total", M_COUNTER, "announcement send errors", NULL, 0},
    {METRICS_ID_SDS_LAST_SUCCESS_TIME_SECONDS, "dvbipi_sds_last_success_time_seconds", M_GAUGE, "unix time of the last successful announcement", NULL, 0},
    {METRICS_ID_BCG_SOURCES_CONFIGURED, "dvbipi_bcg_sources_configured", M_GAUGE, "guide sources configured", NULL, 0},
    {METRICS_ID_BCG_SOURCES_UP, "dvbipi_bcg_sources_up", M_GAUGE, "guide sources currently loaded", NULL, 0},
    {METRICS_ID_BCG_SOURCE_ERRORS_TOTAL, "dvbipi_bcg_source_errors_total", M_COUNTER, "guide source load/parse errors by reason", "reason", 0},
    {METRICS_ID_BCG_SERVICES, "dvbipi_bcg_services", M_GAUGE, "channels in the loaded guide", NULL, 0},
    {METRICS_ID_BCG_SERVICES_WITH_EVENTS, "dvbipi_bcg_services_with_events", M_GAUGE, "channels with an event in the current window", NULL, 0},
    {METRICS_ID_BCG_EVENTS, "dvbipi_bcg_events", M_GAUGE, "events in the current window", NULL, 0},
    {METRICS_ID_BCG_DOCUMENTS_GENERATED_TOTAL, "dvbipi_bcg_documents_generated_total", M_COUNTER, "BCG documents generated", NULL, 0},
    {METRICS_ID_BCG_DOCUMENT_ERRORS_TOTAL, "dvbipi_bcg_document_errors_total", M_COUNTER, "BCG document generation errors", NULL, 0},
    {METRICS_ID_BCG_PUBLICATIONS_TOTAL, "dvbipi_bcg_publications_total", M_COUNTER, "BCG documents published", NULL, 0},
    {METRICS_ID_BCG_PUBLICATION_ERRORS_TOTAL, "dvbipi_bcg_publication_errors_total", M_COUNTER, "BCG publication send errors", NULL, 0},
    {METRICS_ID_BCG_LAST_SUCCESS_TIME_SECONDS, "dvbipi_bcg_last_success_time_seconds", M_GAUGE, "unix time of the last successful publication", NULL, 0},
    {METRICS_ID_BCG_SCHEDULE_START_TIME_SECONDS, "dvbipi_bcg_schedule_start_time_seconds", M_GAUGE, "earliest event start in the current window", NULL, 0},
    {METRICS_ID_BCG_SCHEDULE_END_TIME_SECONDS, "dvbipi_bcg_schedule_end_time_seconds", M_GAUGE, "latest event end in the current window", NULL, 0},
    {METRICS_ID_RIST_SENDER_SENT_TOTAL, "dvbipi_rist_sender_sent_total", M_COUNTER, "packets sent to this RIST peer", "peer", 0},
    {METRICS_ID_RIST_SENDER_RETRANSMITTED_TOTAL, "dvbipi_rist_sender_retransmitted_total", M_COUNTER, "packets retransmitted to this RIST peer", "peer", 0},
    {METRICS_ID_RIST_SENDER_RTT_MILLISECONDS, "dvbipi_rist_sender_rtt_milliseconds", M_GAUGE, "current RTT to this RIST peer", "peer", 0},
    {METRICS_ID_RIST_RECEIVER_RECEIVED_TOTAL, "dvbipi_rist_receiver_received_total", M_COUNTER, "packets received on the RIST flow", NULL, 0},
    {METRICS_ID_RIST_RECEIVER_MISSING_TOTAL, "dvbipi_rist_receiver_missing_total", M_COUNTER, "packets missing on the RIST flow, incl reordered", NULL, 0},
    {METRICS_ID_RIST_RECEIVER_RECOVERED_TOTAL, "dvbipi_rist_receiver_recovered_total", M_COUNTER, "packets recovered via retransmit", NULL, 0},
    {METRICS_ID_RIST_RECEIVER_LOST_TOTAL, "dvbipi_rist_receiver_lost_total", M_COUNTER, "packets never recovered", NULL, 0},
    {METRICS_ID_RIST_RECEIVER_RTT_MILLISECONDS, "dvbipi_rist_receiver_rtt_milliseconds", M_GAUGE, "average RTT across the flow's peers", NULL, 0},
    {METRICS_ID_RIST_RECEIVER_BUFFER_MILLISECONDS, "dvbipi_rist_receiver_buffer_milliseconds", M_GAUGE, "current recovery buffer fill", NULL, 0},
    {METRICS_ID_SRT_SENDER_SENT_TOTAL, "dvbipi_srt_sender_sent_total", M_COUNTER, "packets sent to this SRT peer, incl retransmissions", "peer", 0},
    {METRICS_ID_SRT_SENDER_RETRANSMITTED_TOTAL, "dvbipi_srt_sender_retransmitted_total", M_COUNTER, "packets retransmitted to this SRT peer", "peer", 0},
    {METRICS_ID_SRT_SENDER_RTT_MILLISECONDS, "dvbipi_srt_sender_rtt_milliseconds", M_GAUGE, "current RTT to this SRT peer", "peer", 0},
    {METRICS_ID_SRT_SENDER_LOST_TOTAL, "dvbipi_srt_sender_lost_total", M_COUNTER, "packets the peer reported lost", "peer", 0},
    {METRICS_ID_SRT_SENDER_DROPPED_TOTAL, "dvbipi_srt_sender_dropped_total", M_COUNTER, "packets dropped, too late to send", "peer", 0},
    {METRICS_ID_SRT_RECEIVER_RECEIVED_TOTAL, "dvbipi_srt_receiver_received_total", M_COUNTER, "packets received on the SRT flow", NULL, 0},
    {METRICS_ID_SRT_RECEIVER_LOST_TOTAL, "dvbipi_srt_receiver_lost_total", M_COUNTER, "packets lost, incl later recovered", NULL, 0},
    {METRICS_ID_SRT_RECEIVER_DROPPED_TOTAL, "dvbipi_srt_receiver_dropped_total", M_COUNTER, "packets dropped, too late to play", NULL, 0},
    {METRICS_ID_SRT_RECEIVER_RTT_MILLISECONDS, "dvbipi_srt_receiver_rtt_milliseconds", M_GAUGE, "current RTT on the SRT flow", NULL, 0},
    {METRICS_ID_SRT_RECEIVER_BUFFER_MILLISECONDS, "dvbipi_srt_receiver_buffer_milliseconds", M_GAUGE, "receive buffer delay (TSBPD)", NULL, 0},
    {METRICS_ID_REC_BYTES_TOTAL, "dvbipi_rec_bytes_total", M_COUNTER, "bytes written across all outputs", NULL, 0},
    {METRICS_ID_REC_OUTPUT_UP, "dvbipi_rec_output_up", M_GAUGE, "1 if this output's last write succeeded", "output", 0},
    {METRICS_ID_REC_OUTPUT_ERRORS_TOTAL, "dvbipi_rec_output_errors_total", M_COUNTER, "output write failures", "output", 0},
    {METRICS_ID_REC_ELAPSED_SECONDS, "dvbipi_rec_elapsed_seconds", M_GAUGE, "seconds since recording started", NULL, 0},
    {METRICS_ID_REC_DURATION_LIMIT_SECONDS, "dvbipi_rec_duration_limit_seconds", M_GAUGE, "configured recording duration, 0 if unlimited", NULL, 0},
    {METRICS_ID_DESCRAMBLE_MODE, "dvbipi_descramble_mode", M_INFO, "detected CAS scheme", "mode", 0},
    {METRICS_ID_DESCRAMBLE_KEY_LOAD_ERRORS_TOTAL, "dvbipi_descramble_key_load_errors_total", M_COUNTER, "RSA/device key load failures", NULL, 0},
    {METRICS_ID_DESCRAMBLE_OUTPUT_ERRORS_TOTAL, "dvbipi_descramble_output_errors_total", M_COUNTER, "output emit failures", NULL, 0},
    {METRICS_ID_CAM_CONNECTIONS_ACTIVE, "dvbipi_cam_connections_active", M_GAUGE, "connected cs378x clients", NULL, 0},
    {METRICS_ID_CAM_CONNECTIONS_TOTAL, "dvbipi_cam_connections_total", M_COUNTER, "cs378x client connections accepted", NULL, 0},
    {METRICS_ID_CAM_AUTH_ERRORS_TOTAL, "dvbipi_cam_auth_errors_total", M_COUNTER, "cs378x auth/protocol errors by reason", "reason", 0},
    {METRICS_ID_CAM_SERVICES_ACTIVE, "dvbipi_cam_services_active", M_GAUGE, "services with a live session key", NULL, 0},
    {METRICS_ID_FCC_CHANNELS_ACTIVE, "dvbipi_fcc_channels_active", M_GAUGE, "channels currently tracked", NULL, 0},
    {METRICS_ID_FCC_BURSTS_ACTIVE, "dvbipi_fcc_bursts_active", M_GAUGE, "concurrent FCC burst sessions", NULL, 0},
    {METRICS_ID_FCC_RET_CLIENTS_ACTIVE, "dvbipi_fcc_ret_clients_active", M_GAUGE, "active unicast RET sessions", NULL, 0},
    {METRICS_ID_FCC_BYTES_RETRANSMITTED_TOTAL, "dvbipi_fcc_bytes_retransmitted_total", M_COUNTER, "bytes retransmitted via FCC bursts", NULL, 0},
    {METRICS_ID_FCC_NACKS_TOTAL, "dvbipi_fcc_nacks_total", M_COUNTER, "NACKs handled", NULL, 0},
    {METRICS_ID_FCC_CONGESTION_ADAPTATIONS_TOTAL, "dvbipi_fcc_congestion_adaptations_total", M_COUNTER, "burst rate reduced due to congestion", NULL, 0},
};
#define N_DEFS (sizeof DEFS / sizeof DEFS[0])

typedef struct {
  char *buf;
  size_t len, cap;
} strbuf_t;

/* out of memory: sb->buf stays NULL, every sb_appendf becomes a no-op */
static void sb_init(strbuf_t *sb) {
  sb->cap = 8192;
  sb->len = 0;
  sb->buf = malloc(sb->cap);
  if (!sb->buf) {
    sb->cap = 0;
    return;
  }
  sb->buf[0] = '\0';
}

static void sb_appendf(strbuf_t *sb, const char *fmt, ...)
#if defined(__GNUC__)
    __attribute__((format(printf, 2, 3)))
#endif
    ;

static void sb_appendf(strbuf_t *sb, const char *fmt, ...) {
  if (!sb->buf)
    return;
  for (;;) {
    va_list ap;
    int n;
    char *p;
    va_start(ap, fmt);
    n = vsnprintf(sb->buf + sb->len, sb->cap - sb->len, fmt, ap);
    va_end(ap);
    if (n < 0)
      return;
    if ((size_t)n < sb->cap - sb->len) {
      sb->len += (size_t)n;
      return;
    }
    while (sb->cap - sb->len <= (size_t)n)
      sb->cap *= 2;
    p = realloc(sb->buf, sb->cap);
    if (!p) {
      free(sb->buf);
      sb->buf = NULL;
      sb->len = 0;
      sb->cap = 0;
      return;
    }
    sb->buf = p;
  }
}

/* backslash/quote/newline escaping per OpenMetrics/Prometheus text label-value grammar */
static void escape_label(const char *in, char *out, size_t out_cap) {
  size_t oi = 0;
  for (; *in && oi + 2 < out_cap; in++) {
    if (*in == '\\' || *in == '"') {
      out[oi++] = '\\';
      out[oi++] = *in;
    } else if (*in == '\n') {
      out[oi++] = '\\';
      out[oi++] = 'n';
    } else {
      out[oi++] = *in;
    }
  }
  out[oi] = '\0';
}

/* label named headend_id, not instance: Prometheus already assigns instance
   per scrape target, colliding names get renamed exported_instance */
static void append_base_labels(strbuf_t *sb, const store_slot_t *slot) {
  char esc_headend_id[2 * METRICS_ID_MAX + 2];
  escape_label(slot->metrics_id, esc_headend_id, sizeof esc_headend_id);
  sb_appendf(sb, "component=\"%s\",headend_id=\"%s\"", metrics_component_name(slot->component), esc_headend_id);
}

static void append_composite_input_reason(strbuf_t *sb, const char *label) {
  char input_part[METRICS_LABEL_MAX + 1], reason_part[METRICS_LABEL_MAX + 1];
  char esc_input[2 * METRICS_LABEL_MAX + 2], esc_reason[2 * METRICS_LABEL_MAX + 2];
  const char *sep = strchr(label, METRICS_LABEL_SEP);
  if (sep) {
    size_t ilen = (size_t)(sep - label);
    if (ilen >= sizeof input_part)
      ilen = sizeof input_part - 1;
    memcpy(input_part, label, ilen);
    input_part[ilen] = '\0';
    bufcpy(reason_part, sizeof reason_part, sep + 1);
  } else {
    bufcpy(input_part, sizeof input_part, label);
    reason_part[0] = '\0';
  }
  escape_label(input_part, esc_input, sizeof esc_input);
  escape_label(reason_part, esc_reason, sizeof esc_reason);
  sb_appendf(sb, ",input=\"%s\",reason=\"%s\"", esc_input, esc_reason);
}

#define DEF_ID_MAX 192 /* comfortably above highest metrics_id_t value */

typedef struct {
  const store_slot_t *slot;
  const stored_entry_t *entry;
} entry_ref_t;

static void fill_entry_refs(const store_t *st, const int *def_idx, entry_ref_t *refs, size_t *cursor) {
  for (int si = 0; si < STORE_MAX_INSTANCES; si++) {
    const store_slot_t *slot = &st->slots[si];
    if (!slot->used)
      continue;
    for (int j = 0; j < slot->entry_count; j++) {
      unsigned id = (unsigned)slot->entries[j].id;
      int di = (id < DEF_ID_MAX) ? def_idx[id] : -1;
      if (di >= 0) {
        refs[cursor[(unsigned)di]].slot = slot;
        refs[cursor[(unsigned)di]].entry = &slot->entries[j];
        cursor[(unsigned)di]++;
      }
    }
  }
}

/* one pass over every stored entry, bucketed by def instead of one scan per def */
static void render_grouped(strbuf_t *sb, const store_t *st) {
  int def_idx[DEF_ID_MAX]; /* metrics_id_t -> DEFS[] index, -1 if unused */
  size_t count[N_DEFS], start[N_DEFS], cursor[N_DEFS];
  entry_ref_t *refs = NULL;
  size_t total = 0;

  for (unsigned i = 0; i < DEF_ID_MAX; i++)
    def_idx[i] = -1;
  for (unsigned i = 0; i < N_DEFS; i++) {
    count[i] = 0;
    start[i] = 0;
    if ((unsigned)DEFS[i].id < DEF_ID_MAX)
      def_idx[DEFS[i].id] = (int)i;
  }

  for (int si = 0; si < STORE_MAX_INSTANCES; si++) {
    const store_slot_t *slot = &st->slots[si];
    if (!slot->used)
      continue;
    for (int j = 0; j < slot->entry_count; j++) {
      unsigned id = (unsigned)slot->entries[j].id;
      int di = (id < DEF_ID_MAX) ? def_idx[id] : -1;
      if (di >= 0) {
        count[(unsigned)di]++;
        total++;
      }
    }
  }

  if (total) {
    refs = malloc(sizeof *refs * total);
    if (refs) {
      size_t off = 0;
      for (unsigned i = 0; i < N_DEFS; i++) {
        start[i] = off;
        cursor[i] = off;
        off += count[i];
      }
      fill_entry_refs(st, def_idx, refs, cursor);
    }
  }

  for (unsigned i = 0; i < N_DEFS; i++) {
    const metric_def_t *def = &DEFS[i];
    const char *kind_name = def->kind == M_COUNTER ? "counter" : def->kind == M_INFO ? "info" : "gauge";
    if (!count[i] || !refs)
      continue;
    sb_appendf(sb, "# HELP %s %s\n", def->name, def->help);
    sb_appendf(sb, "# TYPE %s %s\n", def->name, kind_name);
    for (size_t k = start[i]; k < start[i] + count[i]; k++) {
      const store_slot_t *slot = refs[k].slot;
      const stored_entry_t *e = refs[k].entry;
      char esc[2 * METRICS_LABEL_MAX + 2];
      sb_appendf(sb, "%s{", def->name);
      append_base_labels(sb, slot);
      if (def->composite_input_reason) {
        append_composite_input_reason(sb, e->label);
      } else if (def->label_name) {
        escape_label(e->label, esc, sizeof esc);
        sb_appendf(sb, ",%s=\"%s\"", def->label_name, esc);
      }
      sb_appendf(sb, "} %llu\n", (unsigned long long)e->value);
    }
  }
  free(refs);
}

static void render_snapshot_age(strbuf_t *sb, const store_t *st, double now_mono) {
  int any = 0;
  for (int i = 0; i < STORE_MAX_INSTANCES; i++)
    if (st->slots[i].used)
      any = 1;
  if (!any)
    return;

  sb_appendf(sb, "# HELP dvbipi_metrics_snapshot_age_seconds seconds since this instance's last snapshot was received\n");
  sb_appendf(sb, "# TYPE dvbipi_metrics_snapshot_age_seconds gauge\n");
  for (int i = 0; i < STORE_MAX_INSTANCES; i++) {
    const store_slot_t *slot = &st->slots[i];
    if (!slot->used)
      continue;
    sb_appendf(sb, "dvbipi_metrics_snapshot_age_seconds{");
    append_base_labels(sb, slot);
    sb_appendf(sb, "} %.3f\n", now_mono - slot->received_mono);
  }
}

static void render_self_metrics(strbuf_t *sb, const store_t *st) {
  int active = 0;
  for (int i = 0; i < STORE_MAX_INSTANCES; i++)
    if (st->slots[i].used)
      active++;

  sb_appendf(sb, "# HELP dvbipi_metrics_instances exporter instances currently tracked\n");
  sb_appendf(sb, "# TYPE dvbipi_metrics_instances gauge\n");
  sb_appendf(sb, "dvbipi_metrics_instances %d\n", active);

  sb_appendf(sb, "# HELP dvbipi_metrics_snapshots_received_total snapshots accepted and stored\n");
  sb_appendf(sb, "# TYPE dvbipi_metrics_snapshots_received_total counter\n");
  sb_appendf(sb, "dvbipi_metrics_snapshots_received_total %llu\n", (unsigned long long)st->stats.snapshots_received_total);

  sb_appendf(sb, "# HELP dvbipi_metrics_snapshots_rejected_total snapshots rejected by reason\n");
  sb_appendf(sb, "# TYPE dvbipi_metrics_snapshots_rejected_total counter\n");
  sb_appendf(sb, "dvbipi_metrics_snapshots_rejected_total{reason=\"malformed\"} %llu\n", (unsigned long long)st->stats.snapshots_rejected_malformed);
  sb_appendf(sb, "dvbipi_metrics_snapshots_rejected_total{reason=\"stale\"} %llu\n", (unsigned long long)st->stats.snapshots_rejected_stale);
  sb_appendf(sb, "dvbipi_metrics_snapshots_rejected_total{reason=\"full\"} %llu\n", (unsigned long long)st->stats.snapshots_rejected_full);
  sb_appendf(sb, "dvbipi_metrics_snapshots_rejected_total{reason=\"version\"} %llu\n", (unsigned long long)st->stats.snapshots_rejected_version);

  sb_appendf(sb, "# HELP dvbipi_metrics_snapshot_entries_dropped_total entries dropped from accepted snapshots exceeding the per-snapshot entry cap\n");
  sb_appendf(sb, "# TYPE dvbipi_metrics_snapshot_entries_dropped_total counter\n");
  sb_appendf(sb, "dvbipi_metrics_snapshot_entries_dropped_total %llu\n", (unsigned long long)st->stats.snapshot_entries_dropped);

  sb_appendf(sb, "# HELP dvbipi_metrics_http_requests_total /metrics HTTP requests by response status\n");
  sb_appendf(sb, "# TYPE dvbipi_metrics_http_requests_total counter\n");
  sb_appendf(sb, "dvbipi_metrics_http_requests_total{status=\"200\"} %llu\n", (unsigned long long)st->stats.http_requests_200);
  sb_appendf(sb, "dvbipi_metrics_http_requests_total{status=\"404\"} %llu\n", (unsigned long long)st->stats.http_requests_404);
}

void render_openmetrics(const store_t *st, double now_mono, char **out, size_t *out_len) {
  strbuf_t sb;

  sb_init(&sb);
  render_grouped(&sb, st);
  render_snapshot_age(&sb, st, now_mono);
  render_self_metrics(&sb, st);
  sb_appendf(&sb, "# EOF\n");

  *out = sb.buf;
  *out_len = sb.len;
}
