/* Copyright 2026 dvbipitools authors. Licensed under GPL-3.0-or-later.
 * See NOTICE and LICENSE for details and authorship information. */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "lib/helper/ioutil.h"
#include "render.h"

typedef enum { M_GAUGE, M_COUNTER, M_INFO } metric_kind_t;

static const char *metric_kind_name(metric_kind_t k) {
  switch (k) {
    case M_COUNTER: return "counter";
    case M_INFO:    return "info";
    case M_GAUGE:   return "gauge";
  }
  return "gauge";
}

typedef struct {
  metrics_id_t id;
  const char *name;
  metric_kind_t kind;
  const char *help;
  const char *label_name;     /* NULL = no metric-specific label */
  int composite_input_reason; /* label on wire is "input" SEP "reason" */
  int ts_label;
} metric_def_t;

/* order matches protocol.h metric_id_t order, also render order */
static const metric_def_t DEFS[] = {
    {METRICS_ID_HEADEND_INFO, "dvbipi_headend_info", M_INFO, "toolkit build info", "version", 0, 0},
    {METRICS_ID_METRICS_SNAPSHOTS_DROPPED_TOTAL, "dvbipi_metrics_snapshots_dropped_total", M_COUNTER, "snapshots this exporter failed to send", NULL, 0, 0},
    {METRICS_ID_METRICS_PARTS_DROPPED_TOTAL, "dvbipi_metrics_parts_dropped_total", M_COUNTER, "snapshot pieces this exporter failed to send", NULL, 0, 0},
    {METRICS_ID_ERRORS_TOTAL, "dvbipi_errors_total", M_COUNTER, "network errors by reason", "reason", 0, 0},
    {METRICS_ID_OUTPUT_PACKETS_TOTAL, "dvbipi_output_packets_total", M_COUNTER, "packets sent on the output", NULL, 0, 0},
    {METRICS_ID_OUTPUT_BYTES_TOTAL, "dvbipi_output_bytes_total", M_COUNTER, "bytes sent on the output", NULL, 0, 0},
    {METRICS_ID_OUTPUT_ERRORS_TOTAL, "dvbipi_output_errors_total", M_COUNTER, "output send errors", NULL, 0, 0},
    {METRICS_ID_CONFIGURED_SERVICES, "dvbipi_configured_services", M_GAUGE, "services configured", NULL, 0, 0},
    {METRICS_ID_ACTIVE_SERVICES, "dvbipi_active_services", M_GAUGE, "services currently active", NULL, 0, 0},
    {METRICS_ID_INPUT_UP, "dvbipi_input_up", M_GAUGE, "1 if the input is currently connected", "input", 0, 0},
    {METRICS_ID_INPUT_BYTES_TOTAL, "dvbipi_input_bytes_total", M_COUNTER, "bytes read from the input", "input", 0, 0},
    {METRICS_ID_INPUT_RECONNECTS_TOTAL, "dvbipi_input_reconnects_total", M_COUNTER, "input reconnect count", "input", 0, 0},
    {METRICS_ID_INPUT_ERRORS_TOTAL, "dvbipi_input_errors_total", M_COUNTER, "input errors by reason", NULL, 1, 0},
    {METRICS_ID_INPUT_LAST_DATA_TIME_SECONDS, "dvbipi_input_last_data_time_seconds", M_GAUGE, "unix time of the last data received", "input", 0, 0},
    {METRICS_ID_TS_PACKETS_TOTAL, "dvbipi_ts_packets_total", M_COUNTER, "transport stream packets processed", NULL, 0, 1},
    {METRICS_ID_TS_CONTINUITY_ERRORS_TOTAL, "dvbipi_ts_continuity_errors_total", M_COUNTER, "continuity counter errors", NULL, 0, 1},
    {METRICS_ID_TS_DISCONTINUITIES_TOTAL, "dvbipi_ts_discontinuities_total", M_COUNTER, "signaled discontinuities", NULL, 0, 1},
    {METRICS_ID_TS_SYNC_ERRORS_TOTAL, "dvbipi_ts_sync_errors_total", M_COUNTER, "TS sync byte errors", NULL, 0, 1},
    {METRICS_ID_PCR_DISCONTINUITIES_TOTAL, "dvbipi_pcr_discontinuities_total", M_COUNTER, "implausible PCR jumps", NULL, 0, 1},
    {METRICS_ID_PSI_SECTIONS_TOTAL, "dvbipi_psi_sections_total", M_COUNTER, "PSI/SI sections generated by table", "table", 0, 0},
    {METRICS_ID_PSI_ERRORS_TOTAL, "dvbipi_psi_errors_total", M_COUNTER, "PSI/SI section build errors by table", "table", 0, 0},
    {METRICS_ID_CAS_ECMG_CONNECTED, "dvbipi_cas_ecmg_connected", M_GAUGE, "1 if connected to the ECMG", "cas", 0, 0},
    {METRICS_ID_CAS_EMMG_CLIENTS, "dvbipi_cas_emmg_clients", M_GAUGE, "connected EMMG clients", "cas", 0, 0},
    {METRICS_ID_CAS_CRYPTOPERIOD_TRANSITIONS_TOTAL, "dvbipi_cas_cryptoperiod_transitions_total", M_COUNTER, "cryptoperiod transitions", "cas", 0, 0},
    {METRICS_ID_CAS_ECM_TOTAL, "dvbipi_cas_ecm_total", M_COUNTER, "ECMs generated", "cas", 0, 0},
    {METRICS_ID_CAS_ECM_ERRORS_TOTAL, "dvbipi_cas_ecm_errors_total", M_COUNTER, "ECM generation errors", "cas", 0, 0},
    {METRICS_ID_CAS_EMM_TOTAL, "dvbipi_cas_emm_total", M_COUNTER, "EMMs published", "cas", 0, 0},
    {METRICS_ID_CAS_EMM_DROPPED_TOTAL, "dvbipi_cas_emm_dropped_total", M_COUNTER, "EMMs dropped, oversized or send queue full", "cas", 0, 0},
    {METRICS_ID_CAS_SCRAMBLED_PACKETS_TOTAL, "dvbipi_cas_scrambled_packets_total", M_COUNTER, "packets scrambled", NULL, 0, 0},
    {METRICS_ID_CAS_UNEXPECTED_CLEAR_PACKETS_TOTAL, "dvbipi_cas_unexpected_clear_packets_total", M_COUNTER, "clear packets on a managed pid before the ECMG was up", NULL, 0, 0},
    {METRICS_ID_RADIO_AUDIO_FRAMES_TOTAL, "dvbipi_radio_audio_frames_total", M_COUNTER, "audio frames processed by codec", "codec", 0, 0},
    {METRICS_ID_RADIO_AUDIO_FRAMING_ERRORS_TOTAL, "dvbipi_radio_audio_framing_errors_total", M_COUNTER, "audio framing/parse errors", NULL, 0, 0},
    {METRICS_ID_RADIO_METADATA_UPDATES_TOTAL, "dvbipi_radio_metadata_updates_total", M_COUNTER, "metadata updates parsed", NULL, 0, 0},
    {METRICS_ID_RADIO_METADATA_ERRORS_TOTAL, "dvbipi_radio_metadata_errors_total", M_COUNTER, "metadata parse errors", NULL, 0, 0},
    {METRICS_ID_TV_SOURCE_PROGRAM_UP, "dvbipi_tv_source_program_up", M_GAUGE, "1 if the program has at least one active service", NULL, 0, 0},
    {METRICS_ID_TV_SOURCE_PMT_UPDATES_TOTAL, "dvbipi_tv_source_pmt_updates_total", M_COUNTER, "PMT content changes seen", NULL, 0, 0},
    {METRICS_ID_TV_SOURCE_PID_CHANGES_TOTAL, "dvbipi_tv_source_pid_changes_total", M_COUNTER, "elementary stream pid changes seen", NULL, 0, 0},
    {METRICS_ID_TV_REMUX_PACKETS_TOTAL, "dvbipi_tv_remux_packets_total", M_COUNTER, "packets passed through the remux", NULL, 0, 0},
    {METRICS_ID_TV_REMUX_DROPPED_PACKETS_TOTAL, "dvbipi_tv_remux_dropped_packets_total", M_COUNTER, "packets dropped by the remux", NULL, 0, 0},
    {METRICS_ID_TV_AIT_SECTIONS_TOTAL, "dvbipi_tv_ait_sections_total", M_COUNTER, "AIT sections sent", NULL, 0, 0},
    {METRICS_ID_TV_AIT_ERRORS_TOTAL, "dvbipi_tv_ait_errors_total", M_COUNTER, "AIT build errors", NULL, 0, 0},
    {METRICS_ID_TV_EIT_QUEUE_DROPS_TOTAL, "dvbipi_tv_eit_queue_drops_total", M_COUNTER, "EIT sections discarded, reassembly queue full", NULL, 0, 0},
    {METRICS_ID_SDS_SERVICE_PROVIDERS, "dvbipi_sds_service_providers", M_GAUGE, "service providers announced", NULL, 0, 0},
    {METRICS_ID_SDS_SERVICES, "dvbipi_sds_services", M_GAUGE, "services announced", NULL, 0, 0},
    {METRICS_ID_SDS_DOCUMENTS_GENERATED_TOTAL, "dvbipi_sds_documents_generated_total", M_COUNTER, "SD&S documents (re)generated", NULL, 0, 0},
    {METRICS_ID_SDS_DOCUMENT_ERRORS_TOTAL, "dvbipi_sds_document_errors_total", M_COUNTER, "SD&S document generation errors", NULL, 0, 0},
    {METRICS_ID_SDS_ANNOUNCEMENTS_TOTAL, "dvbipi_sds_announcements_total", M_COUNTER, "announcement cycles sent by transport", "transport", 0, 0},
    {METRICS_ID_SDS_ANNOUNCEMENT_ERRORS_TOTAL, "dvbipi_sds_announcement_errors_total", M_COUNTER, "announcement send errors", NULL, 0, 0},
    {METRICS_ID_SDS_LAST_SUCCESS_TIME_SECONDS, "dvbipi_sds_last_success_time_seconds", M_GAUGE, "unix time of the last successful announcement", NULL, 0, 0},
    {METRICS_ID_BCG_SOURCES_CONFIGURED, "dvbipi_bcg_sources_configured", M_GAUGE, "guide sources configured", NULL, 0, 0},
    {METRICS_ID_BCG_SOURCES_UP, "dvbipi_bcg_sources_up", M_GAUGE, "guide sources currently loaded", NULL, 0, 0},
    {METRICS_ID_BCG_SOURCE_ERRORS_TOTAL, "dvbipi_bcg_source_errors_total", M_COUNTER, "guide source load/parse errors by reason", "reason", 0, 0},
    {METRICS_ID_BCG_SERVICES, "dvbipi_bcg_services", M_GAUGE, "channels in the loaded guide", NULL, 0, 0},
    {METRICS_ID_BCG_SERVICES_WITH_EVENTS, "dvbipi_bcg_services_with_events", M_GAUGE, "channels with an event in the current window", NULL, 0, 0},
    {METRICS_ID_BCG_EVENTS, "dvbipi_bcg_events", M_GAUGE, "events in the current window", NULL, 0, 0},
    {METRICS_ID_BCG_DOCUMENTS_GENERATED_TOTAL, "dvbipi_bcg_documents_generated_total", M_COUNTER, "BCG documents generated", NULL, 0, 0},
    {METRICS_ID_BCG_DOCUMENT_ERRORS_TOTAL, "dvbipi_bcg_document_errors_total", M_COUNTER, "BCG document generation errors", NULL, 0, 0},
    {METRICS_ID_BCG_PUBLICATIONS_TOTAL, "dvbipi_bcg_publications_total", M_COUNTER, "BCG documents published", NULL, 0, 0},
    {METRICS_ID_BCG_PUBLICATION_ERRORS_TOTAL, "dvbipi_bcg_publication_errors_total", M_COUNTER, "BCG publication send errors", NULL, 0, 0},
    {METRICS_ID_BCG_LAST_SUCCESS_TIME_SECONDS, "dvbipi_bcg_last_success_time_seconds", M_GAUGE, "unix time of the last successful publication", NULL, 0, 0},
    {METRICS_ID_BCG_SCHEDULE_START_TIME_SECONDS, "dvbipi_bcg_schedule_start_time_seconds", M_GAUGE, "earliest event start in the current window", NULL, 0, 0},
    {METRICS_ID_BCG_SCHEDULE_END_TIME_SECONDS, "dvbipi_bcg_schedule_end_time_seconds", M_GAUGE, "latest event end in the current window", NULL, 0, 0},
    {METRICS_ID_RIST_SENDER_SENT_TOTAL, "dvbipi_rist_sender_sent_total", M_COUNTER, "packets sent to this RIST peer", "peer", 0, 0},
    {METRICS_ID_RIST_SENDER_RETRANSMITTED_TOTAL, "dvbipi_rist_sender_retransmitted_total", M_COUNTER, "packets retransmitted to this RIST peer", "peer", 0, 0},
    {METRICS_ID_RIST_SENDER_RTT_MILLISECONDS, "dvbipi_rist_sender_rtt_milliseconds", M_GAUGE, "current RTT to this RIST peer", "peer", 0, 0},
    {METRICS_ID_RIST_RECEIVER_RECEIVED_TOTAL, "dvbipi_rist_receiver_received_total", M_COUNTER, "packets received on the RIST flow", NULL, 0, 0},
    {METRICS_ID_RIST_RECEIVER_MISSING_TOTAL, "dvbipi_rist_receiver_missing_total", M_COUNTER, "packets missing on the RIST flow, incl reordered", NULL, 0, 0},
    {METRICS_ID_RIST_RECEIVER_RECOVERED_TOTAL, "dvbipi_rist_receiver_recovered_total", M_COUNTER, "packets recovered via retransmit", NULL, 0, 0},
    {METRICS_ID_RIST_RECEIVER_LOST_TOTAL, "dvbipi_rist_receiver_lost_total", M_COUNTER, "packets never recovered", NULL, 0, 0},
    {METRICS_ID_RIST_RECEIVER_RTT_MILLISECONDS, "dvbipi_rist_receiver_rtt_milliseconds", M_GAUGE, "average RTT across the flow's peers", NULL, 0, 0},
    {METRICS_ID_RIST_RECEIVER_BUFFER_MILLISECONDS, "dvbipi_rist_receiver_buffer_milliseconds", M_GAUGE, "current recovery buffer fill", NULL, 0, 0},
    {METRICS_ID_SRT_SENDER_SENT_TOTAL, "dvbipi_srt_sender_sent_total", M_COUNTER, "packets sent to this SRT peer, incl retransmissions", "peer", 0, 0},
    {METRICS_ID_SRT_SENDER_RETRANSMITTED_TOTAL, "dvbipi_srt_sender_retransmitted_total", M_COUNTER, "packets retransmitted to this SRT peer", "peer", 0, 0},
    {METRICS_ID_SRT_SENDER_RTT_MILLISECONDS, "dvbipi_srt_sender_rtt_milliseconds", M_GAUGE, "current RTT to this SRT peer", "peer", 0, 0},
    {METRICS_ID_SRT_SENDER_LOST_TOTAL, "dvbipi_srt_sender_lost_total", M_COUNTER, "packets the peer reported lost", "peer", 0, 0},
    {METRICS_ID_SRT_SENDER_DROPPED_TOTAL, "dvbipi_srt_sender_dropped_total", M_COUNTER, "packets dropped, too late to send", "peer", 0, 0},
    {METRICS_ID_SRT_RECEIVER_RECEIVED_TOTAL, "dvbipi_srt_receiver_received_total", M_COUNTER, "packets received on the SRT flow", NULL, 0, 0},
    {METRICS_ID_SRT_RECEIVER_LOST_TOTAL, "dvbipi_srt_receiver_lost_total", M_COUNTER, "packets lost, incl later recovered", NULL, 0, 0},
    {METRICS_ID_SRT_RECEIVER_DROPPED_TOTAL, "dvbipi_srt_receiver_dropped_total", M_COUNTER, "packets dropped, too late to play", NULL, 0, 0},
    {METRICS_ID_SRT_RECEIVER_RTT_MILLISECONDS, "dvbipi_srt_receiver_rtt_milliseconds", M_GAUGE, "current RTT on the SRT flow", NULL, 0, 0},
    {METRICS_ID_SRT_RECEIVER_BUFFER_MILLISECONDS, "dvbipi_srt_receiver_buffer_milliseconds", M_GAUGE, "receive buffer delay (TSBPD)", NULL, 0, 0},
    {METRICS_ID_REC_BYTES_TOTAL, "dvbipi_rec_bytes_total", M_COUNTER, "bytes written across all outputs", NULL, 0, 0},
    {METRICS_ID_REC_OUTPUT_UP, "dvbipi_rec_output_up", M_GAUGE, "1 if this output's last write succeeded", "output", 0, 0},
    {METRICS_ID_REC_OUTPUT_ERRORS_TOTAL, "dvbipi_rec_output_errors_total", M_COUNTER, "output write failures", "output", 0, 0},
    {METRICS_ID_REC_ELAPSED_SECONDS, "dvbipi_rec_elapsed_seconds", M_GAUGE, "seconds since recording started", NULL, 0, 0},
    {METRICS_ID_REC_DURATION_LIMIT_SECONDS, "dvbipi_rec_duration_limit_seconds", M_GAUGE, "configured recording duration, 0 if unlimited", NULL, 0, 0},
    {METRICS_ID_DESCRAMBLE_MODE, "dvbipi_descramble_mode", M_INFO, "detected CAS scheme", "mode", 0, 0},
    {METRICS_ID_DESCRAMBLE_KEY_LOAD_ERRORS_TOTAL, "dvbipi_descramble_key_load_errors_total", M_COUNTER, "RSA/device key load failures", NULL, 0, 0},
    {METRICS_ID_DESCRAMBLE_OUTPUT_ERRORS_TOTAL, "dvbipi_descramble_output_errors_total", M_COUNTER, "output emit failures", NULL, 0, 0},
    {METRICS_ID_CAM_CONNECTIONS_ACTIVE, "dvbipi_cam_connections_active", M_GAUGE, "connected cs378x clients", NULL, 0, 0},
    {METRICS_ID_CAM_CONNECTIONS_TOTAL, "dvbipi_cam_connections_total", M_COUNTER, "cs378x client connections accepted", NULL, 0, 0},
    {METRICS_ID_CAM_AUTH_ERRORS_TOTAL, "dvbipi_cam_auth_errors_total", M_COUNTER, "cs378x auth/protocol errors by reason", "reason", 0, 0},
    {METRICS_ID_CAM_SERVICES_ACTIVE, "dvbipi_cam_services_active", M_GAUGE, "services with a live session key", NULL, 0, 0},
    {METRICS_ID_FCC_CHANNELS_ACTIVE, "dvbipi_fcc_channels_active", M_GAUGE, "channels currently tracked", NULL, 0, 0},
    {METRICS_ID_FCC_BURSTS_ACTIVE, "dvbipi_fcc_bursts_active", M_GAUGE, "concurrent FCC burst sessions", NULL, 0, 0},
    {METRICS_ID_FCC_RET_CLIENTS_ACTIVE, "dvbipi_fcc_ret_clients_active", M_GAUGE, "active unicast RET sessions", NULL, 0, 0},
    {METRICS_ID_FCC_BYTES_RETRANSMITTED_TOTAL, "dvbipi_fcc_bytes_retransmitted_total", M_COUNTER, "bytes retransmitted via FCC bursts", NULL, 0, 0},
    {METRICS_ID_FCC_NACKS_TOTAL, "dvbipi_fcc_nacks_total", M_COUNTER, "NACKs handled", NULL, 0, 0},
    {METRICS_ID_FCC_CONGESTION_ADAPTATIONS_TOTAL, "dvbipi_fcc_congestion_adaptations_total", M_COUNTER, "burst rate reduced due to congestion", NULL, 0, 0},
    {METRICS_ID_XY_CONNECTIONS_TOTAL, "dvbipi_xy_connections_total", M_COUNTER, "connections accepted, every protocol", NULL, 0, 0},
    {METRICS_ID_XY_CONNECTIONS_ACTIVE, "dvbipi_xy_connections_active", M_GAUGE, "connections currently open", NULL, 0, 0},
    {METRICS_ID_XY_REQUESTS_TOTAL, "dvbipi_xy_requests_total", M_COUNTER, "HTTP requests dispatched", NULL, 0, 0},
    {METRICS_ID_XY_HTTP_ERRORS_TOTAL, "dvbipi_xy_http_errors_total", M_COUNTER, "HTTP responses with a 4xx/5xx status", NULL, 0, 0},
    {METRICS_ID_XY_BYTES_SERVED_TOTAL, "dvbipi_xy_bytes_served_total", M_COUNTER, "wire bytes queued to clients, headers and body", NULL, 0, 0},
    {METRICS_ID_XY_SOURCES_ACTIVE, "dvbipi_xy_sources_active", M_GAUGE, "distinct multicast joins currently open", NULL, 0, 0},
    {METRICS_ID_XY_TSPUSH_SUBS_ACTIVE, "dvbipi_xy_tspush_subscribers_active", M_GAUGE, "raw TS push clients currently attached", NULL, 0, 0},
    {METRICS_ID_TS_BYTES_TOTAL, "dvbipi_ts_bytes_total", M_COUNTER, "transport stream bytes", NULL, 0, 1},
    {METRICS_ID_TS_NULL_PACKETS_TOTAL, "dvbipi_ts_null_packets_total", M_COUNTER, "null packets", NULL, 0, 1},
    {METRICS_ID_TS_SCRAMBLED_PACKETS_TOTAL, "dvbipi_ts_scrambled_packets_total", M_COUNTER, "scrambled packets", NULL, 0, 1},
    {METRICS_ID_TS_CLEAR_PACKETS_TOTAL, "dvbipi_ts_clear_packets_total", M_COUNTER, "unscrambled non-null packets", NULL, 0, 1},
    {METRICS_ID_TS_SYNC_LOSS_TOTAL, "dvbipi_ts_sync_loss_total", M_COUNTER, "TS sync losses", NULL, 0, 1},
    {METRICS_ID_TS_TRANSPORT_ERROR_PACKETS_TOTAL, "dvbipi_ts_transport_error_packets_total", M_COUNTER, "packets with the transport error indicator set", NULL, 0, 1},
    {METRICS_ID_TS_DUPLICATE_PACKETS_TOTAL, "dvbipi_ts_duplicate_packets_total", M_COUNTER, "allowed duplicate packets", NULL, 0, 1},
    {METRICS_ID_TS_PAT_ERRORS_TOTAL, "dvbipi_ts_pat_errors_total", M_COUNTER, "PAT missing or repeated too late", NULL, 0, 1},
    {METRICS_ID_TS_PMT_ERRORS_TOTAL, "dvbipi_ts_pmt_errors_total", M_COUNTER, "PMT missing or repeated too late", NULL, 0, 1},
    {METRICS_ID_TS_CAT_ERRORS_TOTAL, "dvbipi_ts_cat_errors_total", M_COUNTER, "scrambled packets without a CAT", NULL, 0, 1},
    {METRICS_ID_TS_SDT_ERRORS_TOTAL, "dvbipi_ts_sdt_errors_total", M_COUNTER, "SDT actual missing or repeated too late", NULL, 0, 1},
    {METRICS_ID_TS_NIT_ERRORS_TOTAL, "dvbipi_ts_nit_errors_total", M_COUNTER, "NIT actual missing or repeated too late", NULL, 0, 1},
    {METRICS_ID_TS_SDT_OTHER_ERRORS_TOTAL, "dvbipi_ts_sdt_other_errors_total", M_COUNTER, "SDT other repeated too late", NULL, 0, 1},
    {METRICS_ID_TS_NIT_OTHER_ERRORS_TOTAL, "dvbipi_ts_nit_other_errors_total", M_COUNTER, "NIT other repeated too late", NULL, 0, 1},
    {METRICS_ID_TS_EIT_ERRORS_TOTAL, "dvbipi_ts_eit_errors_total", M_COUNTER, "EIT present/following actual missing or repeated too late", NULL, 0, 1},
    {METRICS_ID_TS_EIT_OTHER_ERRORS_TOTAL, "dvbipi_ts_eit_other_errors_total", M_COUNTER, "EIT other repeated too late", NULL, 0, 1},
    {METRICS_ID_TS_RST_ERRORS_TOTAL, "dvbipi_ts_rst_errors_total", M_COUNTER, "sections on the RST pid with another table_id", NULL, 0, 1},
    {METRICS_ID_TS_TDT_ERRORS_TOTAL, "dvbipi_ts_tdt_errors_total", M_COUNTER, "TDT/TOT missing or wrong table_id on its pid", NULL, 0, 1},
    {METRICS_ID_TS_REFERENCED_PID_MISSING_TOTAL, "dvbipi_ts_referenced_pid_missing_total", M_COUNTER, "PMT-referenced pids absent for 5 s", NULL, 0, 1},
    {METRICS_ID_TS_PCR_REPETITION_ERRORS_TOTAL, "dvbipi_ts_pcr_repetition_errors_total", M_COUNTER, "PCR intervals above 100 ms", NULL, 0, 1},
    {METRICS_ID_TS_PTS_ERRORS_TOTAL, "dvbipi_ts_pts_errors_total", M_COUNTER, "video or audio pids without PTS for 700 ms", NULL, 0, 1},
    {METRICS_ID_TS_PID_ADDED_TOTAL, "dvbipi_ts_pid_added_total", M_COUNTER, "pids added to the PMT", NULL, 0, 1},
    {METRICS_ID_TS_PID_REMOVED_TOTAL, "dvbipi_ts_pid_removed_total", M_COUNTER, "pids removed from the PMT", NULL, 0, 1},
    {METRICS_ID_TS_INPUT_STALLS_TOTAL, "dvbipi_ts_input_stalls_total", M_COUNTER, "times no packet arrived for over 1 s", NULL, 0, 1},
    {METRICS_ID_TS_INPUT_STALL_MILLISECONDS_TOTAL, "dvbipi_ts_input_stall_milliseconds_total", M_COUNTER, "milliseconds spent stalled", NULL, 0, 1},
    {METRICS_ID_TS_MAX_INTERPACKET_GAP_MILLISECONDS, "dvbipi_ts_max_interpacket_gap_milliseconds", M_GAUGE, "longest gap between packets, last 30 to 60 s", NULL, 0, 1},
    {METRICS_ID_TS_PCR_MAX_INTERVAL_MILLISECONDS, "dvbipi_ts_pcr_max_interval_milliseconds", M_GAUGE, "longest PCR interval, last 30 to 60 s", NULL, 0, 1},
    {METRICS_ID_TS_LAST_PACKET_TIMESTAMP_SECONDS, "dvbipi_ts_last_packet_timestamp_seconds", M_GAUGE, "unix time of the last packet", NULL, 0, 1},
    {METRICS_ID_TS_TABLE_LAST_SEEN_TIMESTAMP_SECONDS, "dvbipi_ts_table_last_seen_timestamp_seconds", M_GAUGE, "unix time the table was last seen", NULL, 0, 2},
    {METRICS_ID_TS_TABLE_CRC_ERRORS_TOTAL, "dvbipi_ts_table_crc_errors_total", M_COUNTER, "CRC failures by table", NULL, 0, 2},
    {METRICS_ID_TS_TABLE_VERSION_CHANGES_TOTAL, "dvbipi_ts_table_version_changes_total", M_COUNTER, "version changes by table", NULL, 0, 2},
    {METRICS_ID_TS_SI_CRC_ERRORS_TOTAL, "dvbipi_ts_si_crc_errors_total", M_COUNTER, "EIT and TOT CRC failures", NULL, 0, 1},
    {METRICS_ID_TS_UNREFERENCED_PIDS_TOTAL, "dvbipi_ts_unreferenced_pids_total", M_COUNTER, "pids carrying packets that the PMT does not reference", NULL, 0, 1},
    {METRICS_ID_TS_TRANSPORT_STREAM_ID, "dvbipi_ts_transport_stream_id", M_GAUGE, "transport_stream_id from the PAT", NULL, 0, 1},
    {METRICS_ID_TS_PCR_JITTER_MAX_MICROSECONDS, "dvbipi_ts_pcr_jitter_max_microseconds", M_GAUGE, "largest PCR arrival versus PCR value deviation, last 30 to 60 s", NULL, 0, 1},
    {METRICS_ID_SRT_SENDER_QUEUE_CHUNKS, "dvbipi_srt_sender_queue_chunks", M_GAUGE, "chunks waiting in the send queue", "peer", 0, 0},
    {METRICS_ID_SRT_SENDER_QUEUE_CAPACITY_CHUNKS, "dvbipi_srt_sender_queue_capacity_chunks", M_GAUGE, "send queue capacity in chunks", "peer", 0, 0},
    {METRICS_ID_SRT_SENDER_QUEUE_HIGH_WATERMARK_CHUNKS, "dvbipi_srt_sender_queue_high_watermark_chunks", M_GAUGE, "most chunks ever queued", "peer", 0, 0},
    {METRICS_ID_SRT_SENDER_QUEUE_DROPPED_CHUNKS_TOTAL, "dvbipi_srt_sender_queue_dropped_chunks_total", M_COUNTER, "chunks dropped, send queue full", "peer", 0, 0},
    {METRICS_ID_TS_PCR_ACCURACY_ERRORS_TOTAL, "dvbipi_ts_pcr_accuracy_errors_total", M_COUNTER, "PCR pairs whose arrival spacing deviates from their PCR spacing by over 500 ns", NULL, 0, 1},
    {METRICS_ID_TS_PID_PACKETS_TOTAL, "dvbipi_ts_pid_packets_total", M_COUNTER, "packets on an operator listed pid", NULL, 0, 3},
    {METRICS_ID_TS_PID_SCRAMBLED_PACKETS_TOTAL, "dvbipi_ts_pid_scrambled_packets_total", M_COUNTER, "scrambled packets on an operator listed pid", NULL, 0, 3},
    {METRICS_ID_TS_SERVICE_PACKETS_TOTAL, "dvbipi_ts_service_packets_total", M_COUNTER, "packets on the pids of a service", NULL, 0, 4},
    {METRICS_ID_TS_SERVICE_SCRAMBLED_PACKETS_TOTAL, "dvbipi_ts_service_scrambled_packets_total", M_COUNTER, "scrambled packets on the pids of a service", NULL, 0, 4},
    {METRICS_ID_TS_UNREFERENCED_UNLISTED_PIDS_TOTAL, "dvbipi_ts_unreferenced_unlisted_pids_total", M_COUNTER, "unreferenced pids not on the operator's known list", NULL, 0, 1},
    {METRICS_ID_TS_BITRATE_MGB1_BITS_PER_SECOND, "dvbipi_ts_bitrate_mgb1_bits_per_second", M_GAUGE, "TS bitrate, MGB1 profile (1 s slice, 1 s gate, 188 byte packets)", NULL, 0, 1},
    {METRICS_ID_TS_BITRATE_MGB2_BITS_PER_SECOND, "dvbipi_ts_bitrate_mgb2_bits_per_second", M_GAUGE, "TS bitrate, MGB2 profile (100 ms slice, 1 s gate, 188 byte packets)", NULL, 0, 1},
    {METRICS_ID_XY_TSPUSH_QUEUE_BYTES, "dvbipi_xy_tspush_queue_bytes", M_GAUGE, "bytes waiting in the raw TS push client queues", NULL, 0, 0},
    {METRICS_ID_XY_TSPUSH_QUEUE_MAX_BYTES, "dvbipi_xy_tspush_queue_max_bytes", M_GAUGE, "bytes waiting in the fullest raw TS push client queue", NULL, 0, 0},
    {METRICS_ID_XY_TSPUSH_QUEUE_HIGH_WATERMARK_BYTES, "dvbipi_xy_tspush_queue_high_watermark_bytes", M_GAUGE, "most bytes ever waiting in one raw TS push client queue", NULL, 0, 0},
    {METRICS_ID_XY_TSPUSH_QUEUE_DROPPED_TOTAL, "dvbipi_xy_tspush_queue_dropped_total", M_COUNTER, "writes dropped, raw TS push client queue full", NULL, 0, 0},
    {METRICS_ID_TS_UNREFERENCED_PACKETS_TOTAL, "dvbipi_ts_unreferenced_packets_total", M_COUNTER, "packets on pids the PMT does not reference", NULL, 0, 1},
};
#define N_DEFS (sizeof DEFS / sizeof DEFS[0])

/* backslash/quote/newline escaping per OpenMetrics/Prometheus text label-value grammar */
static void escape_label(const char *in, char *out, size_t out_cap) {
  size_t oi = 0;
  for (; *in && oi + 2 < out_cap; in++) {
    if (*in == '\\' || *in == '"') {
      out[oi++] = '\\';
      out[oi++] = *in;
    } else if (*in == '\n') {
      out[oi++] = '\\';
      out[oi++] = 'n';
    } else {
      out[oi++] = *in;
    }
  }
  out[oi] = '\0';
}

/* label named headend_id, not instance: Prometheus already assigns instance
   per scrape target, colliding names get renamed exported_instance */
static void append_base_labels(dstrbuf_t *sb, const store_slot_t *slot) {
  char esc_headend_id[2 * METRICS_ID_MAX + 2];
  escape_label(slot->metrics_id, esc_headend_id, sizeof esc_headend_id);
  dstrbuf_add(sb, "component=\"");
  dstrbuf_add(sb, metrics_component_name(slot->component));
  dstrbuf_add(sb, "\",headend_id=\"");
  dstrbuf_add(sb, esc_headend_id);
  dstrbuf_add(sb, "\"");
}

static void append_composite_input_reason(dstrbuf_t *sb, const char *label) {
  char input_part[METRICS_LABEL_MAX + 1], reason_part[METRICS_LABEL_MAX + 1];
  char esc_input[2 * METRICS_LABEL_MAX + 2], esc_reason[2 * METRICS_LABEL_MAX + 2];
  const char *sep = strchr(label, METRICS_LABEL_SEP);
  if (sep) {
    size_t ilen = (size_t)(sep - label);
    if (ilen >= sizeof input_part)
      ilen = sizeof input_part - 1;
    memcpy(input_part, label, ilen);
    input_part[ilen] = '\0';
    bufcpy(reason_part, sizeof reason_part, sep + 1);
  } else {
    bufcpy(input_part, sizeof input_part, label);
    reason_part[0] = '\0';
  }
  escape_label(input_part, esc_input, sizeof esc_input);
  escape_label(reason_part, esc_reason, sizeof esc_reason);
  dstrbuf_add(sb, ",input=\"");
  dstrbuf_add(sb, esc_input);
  dstrbuf_add(sb, "\",reason=\"");
  dstrbuf_add(sb, esc_reason);
  dstrbuf_add(sb, "\"");
}

static void append_ts_labels(dstrbuf_t *sb, const char *label, int kind) {
  char stream[METRICS_LABEL_MAX + 1];
  char esc[2 * METRICS_LABEL_MAX + 2];
  const char *sep = kind >= 2 ? strchr(label, METRICS_LABEL_SEP) : NULL;
  size_t n = sep ? (size_t)(sep - label) : strlen(label);

  if (!label[0]) return;
  memcpy(stream, label, n);
  stream[n] = '\0';
  dstrbuf_add(sb, ",direction=\"");
  dstrbuf_add(sb, strncmp(stream, "in", 2) == 0 ? "input" : "output");
  dstrbuf_add(sb, "\",stream=\"");
  escape_label(stream, esc, sizeof esc);
  dstrbuf_add(sb, esc);
  dstrbuf_add(sb, "\"");
  if (sep) {
    escape_label(sep + 1, esc, sizeof esc);
    dstrbuf_add(sb, kind == 4 ? ",service=\"" : kind == 3 ? ",pid=\"" : ",table=\"");
    dstrbuf_add(sb, esc);
    dstrbuf_add(sb, "\"");
  }
}

#define DEF_ID_MAX 300 /* comfortably above highest metrics_id_t value */

typedef struct {
  const store_slot_t *slot;
  const char *label;
  size_t label_len;
  uint64_t value;
} entry_ref_t;

static void count_entries(const store_t *st, const int *def_idx, size_t *count, size_t *total) {
  for (int si = 0; si < STORE_MAX_INSTANCES; si++) {
    const store_slot_t *slot = &st->slots[si];
    metrics_reader_t r;
    metrics_id_t id;
    const char *label;
    size_t label_len;
    uint64_t value;
    if (!slot->valid) continue;
    metrics_reader_init_body(&r, slot->version, slot->live.data, slot->live.len);
    while (metrics_reader_next_ref(&r, &id, &label, &label_len, &value) == 1) {
      int di = ((unsigned)id < DEF_ID_MAX) ? def_idx[id] : -1;
      if (di >= 0) {
        count[(unsigned)di]++;
        (*total)++;
      }
    }
  }
}

static void fill_entry_refs(const store_t *st, const int *def_idx, entry_ref_t *refs, size_t *cursor) {
  for (int si = 0; si < STORE_MAX_INSTANCES; si++) {
    const store_slot_t *slot = &st->slots[si];
    metrics_reader_t r;
    metrics_id_t id;
    const char *label;
    size_t label_len;
    uint64_t value;
    if (!slot->valid) continue;
    metrics_reader_init_body(&r, slot->version, slot->live.data, slot->live.len);
    while (metrics_reader_next_ref(&r, &id, &label, &label_len, &value) == 1) {
      int di = ((unsigned)id < DEF_ID_MAX) ? def_idx[id] : -1;
      if (di >= 0) {
        entry_ref_t *ref = &refs[cursor[(unsigned)di]++];
        ref->slot = slot;
        ref->label = label;
        ref->label_len = label_len;
        ref->value = value;
      }
    }
  }
}

/* one pass over every stored entry, bucketed by def instead of one scan per def */
static void render_grouped(dstrbuf_t *sb, const store_t *st) {
  int def_idx[DEF_ID_MAX]; /* metrics_id_t -> DEFS[] index, -1 if unused */
  size_t count[N_DEFS], start[N_DEFS];
  entry_ref_t *refs = NULL;
  size_t total = 0;
  for (unsigned i = 0; i < DEF_ID_MAX; i++) def_idx[i] = -1;
  for (unsigned i = 0; i < N_DEFS; i++) {
    count[i] = 0;
    start[i] = 0;
    if ((unsigned)DEFS[i].id < DEF_ID_MAX) def_idx[DEFS[i].id] = (int)i;
  }

  count_entries(st, def_idx, count, &total);

  if (total) {
    refs = malloc(sizeof *refs * total);
    if (refs) {
      size_t cursor[N_DEFS];
      size_t off = 0;
      for (unsigned i = 0; i < N_DEFS; i++) {
        start[i] = off;
        cursor[i] = off;
        off += count[i];
      }
      fill_entry_refs(st, def_idx, refs, cursor);
    }
  }

  for (unsigned i = 0; i < N_DEFS; i++) {
    const metric_def_t *def = &DEFS[i];
    if (!count[i] || !refs) continue;
    dstrbuf_add(sb, "# HELP ");
    dstrbuf_add(sb, def->name);
    dstrbuf_add(sb, " ");
    dstrbuf_add(sb, def->help);
    dstrbuf_add(sb, "\n# TYPE ");
    dstrbuf_add(sb, def->name);
    dstrbuf_add(sb, " ");
    dstrbuf_add(sb, metric_kind_name(def->kind));
    dstrbuf_add(sb, "\n");
    for (size_t k = start[i]; k < start[i] + count[i]; k++) {
      const entry_ref_t *e = &refs[k];
      char label[METRICS_LABEL_MAX + 1];
      memcpy(label, e->label, e->label_len);
      label[e->label_len] = '\0';
      dstrbuf_add(sb, def->name);
      dstrbuf_add(sb, "{");
      append_base_labels(sb, e->slot);
      if (def->ts_label) {
        append_ts_labels(sb, label, def->ts_label);
      } else if (def->composite_input_reason) {
        append_composite_input_reason(sb, label);
      } else if (def->label_name) {
        char esc[2 * METRICS_LABEL_MAX + 2];
        escape_label(label, esc, sizeof esc);
        dstrbuf_add(sb, ",");
        dstrbuf_add(sb, def->label_name);
        dstrbuf_add(sb, "=\"");
        dstrbuf_add(sb, esc);
        dstrbuf_add(sb, "\"");
      }
      dstrbuf_add(sb, "} ");
      dstrbuf_add_u64(sb, e->value);
      dstrbuf_add(sb, "\n");
    }
  }
  free(refs);
}

static void add_head(dstrbuf_t *sb, const char *name, const char *type, const char *help) {
  dstrbuf_add(sb, "# HELP ");
  dstrbuf_add(sb, name);
  dstrbuf_add(sb, " ");
  dstrbuf_add(sb, help);
  dstrbuf_add(sb, "\n# TYPE ");
  dstrbuf_add(sb, name);
  dstrbuf_add(sb, " ");
  dstrbuf_add(sb, type);
  dstrbuf_add(sb, "\n");
}

static void add_sample(dstrbuf_t *sb, const char *series, uint64_t value) {
  dstrbuf_add(sb, series);
  dstrbuf_add(sb, " ");
  dstrbuf_add_u64(sb, value);
  dstrbuf_add(sb, "\n");
}

static void render_snapshot_age(dstrbuf_t *sb, const store_t *st, double now_mono) {
  int any = 0;
  for (int i = 0; i < STORE_MAX_INSTANCES; i++) if (st->slots[i].valid) any = 1;
  if (!any) return;

  add_head(sb, "dvbipi_metrics_snapshot_age_seconds", "gauge", "seconds since this instance's last snapshot was received");
  for (int i = 0; i < STORE_MAX_INSTANCES; i++) {
    const store_slot_t *slot = &st->slots[i];
    if (!slot->valid) continue;
    dstrbuf_add(sb, "dvbipi_metrics_snapshot_age_seconds{");
    append_base_labels(sb, slot);
    dstrbuf_appendf(sb, "} %.3f\n", now_mono - slot->received_mono);
  }
}

static void render_self_metrics(dstrbuf_t *sb, const store_t *st) {
  uint64_t active = 0;
  for (int i = 0; i < STORE_MAX_INSTANCES; i++) if (st->slots[i].valid) active++;

  add_head(sb, "dvbipi_metrics_instances", "gauge", "exporter instances currently tracked");
  add_sample(sb, "dvbipi_metrics_instances", active);

  add_head(sb, "dvbipi_metrics_snapshots_received_total", "counter", "snapshots accepted and stored");
  add_sample(sb, "dvbipi_metrics_snapshots_received_total", st->stats.snapshots_received_total);

  add_head(sb, "dvbipi_metrics_snapshots_rejected_total", "counter", "snapshots rejected by reason");
  add_sample(sb, "dvbipi_metrics_snapshots_rejected_total{reason=\"malformed\"}", st->stats.snapshots_rejected_malformed);
  add_sample(sb, "dvbipi_metrics_snapshots_rejected_total{reason=\"stale\"}", st->stats.snapshots_rejected_stale);
  add_sample(sb, "dvbipi_metrics_snapshots_rejected_total{reason=\"full\"}", st->stats.snapshots_rejected_full);
  add_sample(sb, "dvbipi_metrics_snapshots_rejected_total{reason=\"version\"}", st->stats.snapshots_rejected_version);
  add_sample(sb, "dvbipi_metrics_snapshots_rejected_total{reason=\"toolarge\"}", st->stats.snapshots_rejected_toolarge);

  add_head(sb, "dvbipi_metrics_snapshots_incomplete_total", "counter", "snapshots discarded because a piece of them was lost");
  add_sample(sb, "dvbipi_metrics_snapshots_incomplete_total", st->stats.snapshots_incomplete);

  add_head(sb, "dvbipi_metrics_parts_orphaned_total", "counter", "stray snapshot pieces dropped");
  add_sample(sb, "dvbipi_metrics_parts_orphaned_total", st->stats.parts_orphaned);

  add_head(sb, "dvbipi_metrics_http_requests_total", "counter", "/metrics HTTP requests by response status");
  add_sample(sb, "dvbipi_metrics_http_requests_total{status=\"200\"}", st->stats.http_requests_200);
  add_sample(sb, "dvbipi_metrics_http_requests_total{status=\"404\"}", st->stats.http_requests_404);
}

void render_openmetrics(const store_t *st, double now_mono, char **out, size_t *out_len) {
  dstrbuf_t sb;
  dstrbuf_init(&sb);
  render_grouped(&sb, st);
  render_snapshot_age(&sb, st, now_mono);
  render_self_metrics(&sb, st);
  dstrbuf_add(&sb, "# EOF\n");
  *out = sb.buf;
  *out_len = sb.len;
}
