/* Copyright 2026 dvbipitools authors. Licensed under GPL-3.0-or-later.
 * See NOTICE and LICENSE for details and authorship information. */

#include <stdio.h>

#include "priv.h"
#include "../version.h"

void fccret_print_help(void) {
  printf(
  "usage: %s -g <range> -l <addr>:<port> -I <iface> [options]\n\n"
  "RTP retransmission (RET, Annex F) and Fast Channel Change (FCC/RAMS, Annex I) server\n\n"
  "options:\n"
  "  -g, --range <cidr>[,<cidr>...]   multicast range(s) to capture, IPv4 or IPv6\n"
  "  -l, --listen <addr>:<port>       unicast bind, shared by RET and FCC traffic\n"
  "  -I, --iface <iface>              capture interface (required)\n"
  "  -M, --max-channels <n>           pre-allocated channel slots (default: 0 = 300)\n"
  "      --channel-idle-timeout <s>   free a channel slot after this many seconds with no\n"
  "                                   packets (default: 120, 0 = never reap)\n"
  "  -R, --rtx-pt <n>                 RTP payload type for retransmitted/burst packets (default: 99)\n"
  "  -w, --workers <n>                -l socket worker threads (default: 0 = online CPU cores)\n"
  "      --cpu-affinity <spec>        pin pacer threads to CPUs: off|auto|2-4,6,8 (default: off)\n"
  "  -u, --user <user>                drop privileges to this user after opening the capture handle\n"
  "  -v, --verbose                    periodic stats on stderr\n"
  "      --color <when>               auto|always|never (default auto)\n"
  "      --metrics <path>             socket for metrics (default: /run/dvbipitools/metrics.sock)\n"
  "      --metrics-id <name>          stable instance id; metrics disabled unless set\n"
  "      --metrics-interval <s>       snapshot interval in seconds (default: 5)\n"
  "      --metrics-inspect-ts <lvl>   TS health metrics: off|basic|medium|full (default: off)\n"
  "  -d, --daemonize                  fork to background after startup, detach from terminal\n"
  "  -c, --config <path>              YAML config file (default: %s, if present)\n"
  "      --config-strict              fail on config file issues instead of warnings\n"
  "      --configtest                 check the config file, then exit\n"
  "  -h, --help                       this help\n\n"
  "RET (Annex F) options:\n"
  "      --no-ret                     disable RET entirely\n"
  "  -B, --buffer <ms>                per-channel retransmission buffer depth (default: 2000)\n"
  "  -F, --ff-port <port>             multicast RET session port (default: 0 = original channel's port)\n"
  "      --no-mc-ret                  disable the multicast RET session, unicast-only repair\n"
  "      --max-ret-clients <n>        pre-allocated unicast RTX per-client sequence slots,\n"
  "                                   F.3.2.1 (default: 16384)\n"
  "      --ret-client-idle-timeout <s> free a unicast RTX client slot after this many\n"
  "                                   seconds with no NACKs (default: 300, 0 = never reap)\n"
  "      --no-rsi                     disable RSI self-announcement\n"
  "      --rsi-interval <s>           RSI self-announcement interval, IPv4 -l only (default: 5)\n"
  "      --rsi-mc-ret                 RSI (F.5.3) rides MC RET session, not default session,\n"
  "                                   requires MC RET, matches dipisds --ret-rsi-mc-ret\n"
  "      --rsi-hostname <name>        announce this DNS name (SRBT 2) instead of -l's IPv4\n"
  "                                   address (SRBT 0) in RSI\n\n"
  "FCC (Annex I) options:\n"
  "      --no-fcc                     disable FCC entirely\n"
  "  -G, --gop-cap <ms>               safety cap on cached GOP-in-progress duration (default: 8000)\n"
  "  -C, --max-bursts <n>             pre-allocated concurrent burst-session slots (default: 4096)\n"
  "  -X, --burst-multiplier <n>       burst rate as multiple of observed nominal bitrate (default: 1.5)\n"
  "  -D, --burst-duration-cap <ms>    hard max burst duration regardless of signaling (default: 10000)\n"
  "      --max-buffer-fill-bound <ms> reject a RAMS-R Min RAMS Buffer Fill Requirement above this\n"
  "                                   (RFC 6285 Sec 10 DoS mitigation, default: 30000, 0 = no bound)\n"
  "      --fcc-resolve-by-port        resolve ignore-media-ssrc RAMS-R by dedicated per-channel\n"
  "                                   port instead of rejecting with 510 (default: off)\n"
  "      --fcc-resolve-base-port <p>  base port for --fcc-resolve-by-port (default: 0 = -l port + 1)\n"
  "      --congestion-nack-threshold <n>  NACKs during one burst before terminating it as\n"
  "                                   congested (RFC 6285 Sec 6.4, default: 5, 0 = disabled)\n"
  "      --fcc-range <cidr>[,...]     restrict FCC to these -g sub-ranges (default: all of -g)\n"
  "      --fcc-client-range <cidr>[,...] restrict FCC requests to these client source ranges\n"
  "                                   (default: any client)\n\n"
  "example:\n"
  "  %s -g 239.0.0.0/8 -l 10.0.0.1:6000 -I eth0\n",
  TOOL_NAME, DEFAULT_CONFIG_PATH, TOOL_NAME);
}
