/* Copyright 2026 dvbipitools authors. Licensed under GPL-3.0-or-later.
 * See NOTICE and LICENSE for details and authorship information. */

#include <stdio.h>

#include "priv.h"
#include "../version.h"

void sds_print_help(void) {
  printf(
    "usage: %s -a -i <path> -m <mcast>:<port> [options]\n"
    "       %s -l -m <mcast>:<port> [options]\n\n"
    "DVBSTP / SD&S (ETSI TS 102 034) service discovery: announce a service list on\n"
    "multicast, or listen for one and write a playlist\n\n"
    "options:\n"
    "  -a, --announce          headend mode: read -i, transmit on -m\n"
    "  -l, --listen            client mode: receive on -m, write -o\n"
    "  -m, --mcast <g>:<p>     multicast group:port ([addr6]:port for v6)\n"
    "  -I, --iface <iface>     multicast interface\n"
    "  -v, --verbose           periodic stats on stderr\n"
    "      --color <when>      auto|always|never (default auto)\n"
    "  -d, --daemonize         fork to background after startup, detach from terminal\n"
    "  -c, --config <path>     YAML config file (default: %s, if present)\n"
    "      --config-strict     fail on config file issues instead of warnings\n"
    "      --configtest        check the config file, then exit\n"
    "  -h, --help              this help\n\n"
    "listen mode options:\n"
    "  -t, --timeout <s>       stop after N seconds (default 35)\n"
    "  -o, --output <path>     output path, - for stdout (default)\n"
    "  -f, --format <fmt>      m3u|csv|xspf|xml|null (default from -o suffix)\n\n"
    "announce mode options:\n"
    "  -i, --input <path>      .csv/.m3u/.xspf playlist or raw SD&S .xml\n"
    "  -p, --provider <name>   DomainName (required unless -i is .xml)\n"
    "  -O, --offering <name>   display name (required unless -i is .xml)\n"
    "  -L, --lang <code>       ISO 639-2 for the display name (default deu)\n"
    "      --dscp <v>          output DSCP marking: video-high|video-low|voice|\n"
    "                          signalling|best-effort|0..63 (default: signalling)\n"
    "  -t, --interval <s>      repeat interval (default 5)\n"
    "      --ret-addr <a>:<p>  advertise a dipifccret RET server (its -l value);\n"
    "                          opt-in, adds RTPRetransmission to every announced service\n"
    "      --ret-rtx-time <ms> RET rtx-time, matches dipifccret -B (default 2000)\n"
    "      --ret-rtx-pt <n>    RET RTP payload type, matches dipifccret -R (default 99)\n"
    "      --ret-mc            also advertise multicast RET (dipifccret without --no-mc-ret)\n"
    "      --ret-mc-port <p>   multicast RET port, matches dipifccret -F (default: service port)\n"
    "      --ret-rsi-mc-ret    RSI (F.5.3) rides the MC RET session, not the default\n"
    "                          session; requires --ret-mc, matches dipifccret --rsi-mc-ret\n"
    "      --fcc-addr <a>:<p>  advertise a dipifccret FCC server (its -l value);\n"
    "                          opt-in, adds ServerBasedEnhancementServiceInfo to every service\n"
    "      --fcc-rtx-time <ms> FCC Retransmission_session rtx-time (default 2000)\n"
    "      --fcc-rtx-pt <n>    FCC RTP payload type, matches dipifccret -R (default 99)\n"
    "      --fcc-resolve-by-port          per-service FCC port instead of --fcc-addr's port\n"
    "      --fcc-resolve-base-port <p>    matches dipifccret --fcc-resolve-base-port\n"
    "      --fcc-resolve-max-channels <n> port hash modulus for resolve-by-port (default 300)\n"
    "      --al-fec-addr <a>:<p>          advertise an Annex E Layer 1 FEC repair stream\n"
    "      --al-fec-pt <n>     FEC repair stream RTP payload type (default 96)\n"
    "      --metrics <path>    Unix datagram socket for metrics (default: /run/dvbipitools/metrics.sock)\n"
    "      --metrics-id <name> stable instance id; metrics disabled unless set\n"
    "      --metrics-interval <s> a: snapshot interval in seconds (default: 5)\n"
    "      --packages <path>   Package Discovery from id,name,lang,visible,svc1|svc2|... lines\n"
    "      --cells <path>      Regionalisation Discovery from id,country,type:value,... lines\n"
    "      --rms-name <name>   RMS Discovery display name; requires --rms-location\n"
    "      --rms-lang <code>   ISO 639-2 for --rms-name (default deu)\n"
    "      --rms-location <uri>          RMSType RMSLocation\n"
    "      --rms-logo <uri>    RMSType LogoURI\n"
    "      --fus-name <name>   FUS Discovery display name; requires --fus-id\n"
    "      --fus-lang <code>   ISO 639-2 for --fus-name (default deu)\n"
    "      --fus-id <n>        FUSID (decimal)\n"
    "      --fus-announce <a>:<p>        FUS MulticastAnnouncementAddress\n"
    "      --fus-logo <uri>    FUSType LogoURI\n\n"
    "examples:\n"
    "  %s -a -i channels.csv -p example.org -O \"My Headend\" -m 239.255.0.1:3937\n"
    "  %s -l -m 239.255.0.1:3937 -o discovered.m3u\n",
    TOOL_NAME, TOOL_NAME, DEFAULT_CONFIG_PATH, TOOL_NAME, TOOL_NAME);
}
