/* Copyright 2026 dvbipitools authors. Licensed under GPL-3.0-or-later.
 * See NOTICE and LICENSE for details and authorship information. */

#include <stdio.h>

#include "priv.h"
#include "../version.h"

void dixy_print_help(void) {
  printf(
  "usage: %s [options]\n\n"
  "serve streams over HTTP(S) as raw TS push, HLS, LL-HLS, MPEG-DASH or LL-DASH.\n"
  "It includes clients for FCC, RET(RAMS) and AL-FEC, also acts as a DLNA MediaServer.\n\n"
  "options:\n"
  "  -I, --iface <iface>            interface name for multicast joins      [kernel]\n"
  "  -l, --listen <a>:<p>           HTTP listen address:port                [all:9080]\n"
  "  -L, --listen-tls <a>:<p>       HTTPS listen address:port               [all:9443]\n"
  "      --tls-cert <path>          certificate file (PEM)\n"
  "      --tls-key <path>           private key file (PEM)\n"
  "  -j, --workers <spec>           -1/-2/-3: that many x cpu cores,\n"
  "                                 or <N>: an absolute thread count        [-1]\n"
  "      --cpu-affinity <spec>      pin workers to CPUs: off|auto|2-4,6,8   [off]\n"
  "      --max-clients <n>          cap on concurrent streams               [256]\n"
  "      --max-channels <n>         cap on concurrent\n"
  "                                 (source,filter,pmt,container)           [32]\n"
  "      --idle-timeout <s>         close a conn idle this long, 0 = off    [0]\n"
  "      --capture-ring-size <n>    per-source ingress ring buffer, KiB     [4096]\n"
  "      --ts-startup-timeout <s>   ts/spts/rawaudio: wait this long for a source's\n"
  "                                 first packet before 504, 0 = off          [5]\n"
  "  -i, --input <source>           add an input, repeatable, by form:\n"
  "                                 -                      stdin, /stdin/<fmt>\n"
  "                                 rist://@host:port      RIST, /rist/<fmt>\n"
  "                                 sds://addr:port        live SD&S/DVBSTP\n"
  "                                 rtp://addr:port        direct multicast, RTP\n"
  "                                 udp://addr:port        direct multicast, plain TS\n"
  "                                 http(s)://url          raw TS/RTP source\n"
  "                                 *.m3u/.xspf/.csv/.xml  playlist file\n"
  "                                 list index = position among all -i flags, so\n"
  "                                 a -/rist:// slot leaves that number unused\n"
  "  -n, --name <name>              name the -i right before it; that name can then\n"
  "                                 be used in URLs instead of /list/<n>/ or /rist//stdin\n"
  "                                 no '/', no leading '.', not a reserved word, unique\n"
  "      --media-type <t>           radio|tv, DLNA upnp:class               [tv]\n"
  "  -J, --join-all                 join all inputs at startup, never leave [off]\n"
  "  -k, --insecure                 skip TLS verification on https:// input\n"
  "      --sds-timeout <s>          sds:// discovery wait at startup/reload [3]\n"
  "      --sds-refresh-interval <s> sds:// re-poll period               [30]\n"
  "      --segment-size <s>         target segment duration, seconds        [3]\n"
  "                                 (hls, hls-fmp4, llhls, dash, lldash)\n"
  "      --segment-count <n>        playlist/manifest sliding-window size   [4]\n"
  "      --hls-part-size <s>        LL-HLS target part duration, seconds    [0.35]\n"
  "      --dash-part-size <s>       LL-DASH target chunk duration, seconds  [0.333]\n"
  "      --dash-utc-url <url>       LL-DASH MPD UTCTiming source, http-xsiso\n"
  "                                 [http://time.akamai.com/?iso&ms]\n"
  "      --hls-seg-pool <n>         segment buffer freelist cap per size    [8]\n"
  "      --metrics <path>           metrics sock [/run/dvbipitools/metrics.sock]\n"
  "      --metrics-id <name>        stable instance id, disabled if not set\n"
  "      --metrics-interval <s>     snapshot interval (default: 5 seconds)\n"
  "      --metrics-inspect-ts <lvl> TS health metrics: off|basic|medium|full (default: off)\n"
  "      --metrics-http             also serve /metrics ourselves           [off]\n"
  "      --metrics-auth <u>:<p>     HTTP Basic Auth for GET /metrics        [off]\n"
  "  -f, --format <list>            comma-separated route whitelist, from\n"
  "                                 ts,spts,rawaudio,hls,llhls,dash,lldash  [all]\n"
  "      --no-url-rtp               disable /rtp/... routes\n"
  "      --no-url-udp               disable /udp/... routes\n"
  "      --no-url-srt               disable /srt/... routes\n"
  "      --no-pid-filters           ignore ?filter= on every route\n"
  "      --no-lcevc                 ignore ?lcevc= on every route\n"
  "      --no-http2                 disable HTTP/2\n"
  "      --no-http3                 disable HTTP/3\n"
  "      --no-fcc                   ignore SDS fcc\n"
  "      --no-ret                   ignore SDS ret\n"
  "      --al-fec <L>:<D>           Annex E Layer 1 FEC (SMPTE 2022-1) matrix size for any\n"
  "                                 SDS-advertised repair stream, L*D<=400, L<=40\n"
  "      --no-al-fec                ignore SDS FECBaseLayer\n"
  "      --no-status                disable /ui/status.js\n"
  "      --h3-altsvc-port <n>       port announced in Alt-Svc               [TLS port]\n"
  "      --h3-max-streams <n>       concurrent requests per HTTP/3 conn     [100]\n"
  "      --h3-max-conns <n>         HTTP/3 conns per worker, upper bound    [256]\n"
  "      --h3-idle-timeout <s>      HTTP/3 connection idle timeout          [30]\n"
  "      --h3-retry <mode>          HTTP/3 addr validation: off|auto|always [auto]\n"
  "      --h3-max-udp-payload <n>   largest HTTP/3 UDP datagram, 1200..65507 [1452]\n"
  "      --h3-window <KiB>          HTTP/3 receive window per stream        [256]\n"
  "      --h3-cc <algo>             HTTP/3 congestion ctrl: cubic|bbr|reno  [cubic]\n"
  "      --status-tpl <path>        use file instead of the built-in page\n"
  "      --auth <user:pass>         HTTP Basic Auth for /, /ui/status.js, /ui/ws/  [off]\n"
  "      --cors-origin <list>       comma-separated hls/hls-fmp4/llhls/dash/lldash\n"
  "                                 origins  [\"*\"]\n"
  "      --ssdp-ttl <n>             SSDP multicast TTL                      [3]\n"
  "      --ssdp-iface <iface>       interface for SSDP announce/reply       [kernel]\n"
  "      --ssdp-interval <s>        SSDP NOTIFY re-announce period          [60]\n"
  "      --ssdp-max-age <s>         CACHE-CONTROL max-age, >= 2x interval   [1800]\n"
  "      --enable-dlna              serve SSDP + a UPnP MediaServer (DLNA)  [off]\n"
  "      --dlna-host <h>[:<p>]      host[:port] advertised in SSDP/DIDL     [-l/--listen]\n"
  "      --dlna-name <name>         DLNA friendlyName                       [%s (host)]\n"
  "      --dlna-keep-multicast      rtp/udp items: dvb-igmp/dvb-mld, mgroup [off]\n"
  "  -d, --daemonize                fork to background after startup\n"
  "  -v, --verbose                  per-connection diagnostics on stderr\n"
  "      --color <when>             auto|always|never                       [auto]\n"
  "  -c, --config <path>            YAML config file                        [%s, if present]\n"
  "      --config-strict            fail on config file issues instead of warnings\n"
  "      --configtest               check the config file, then exit\n"
  "  -h, --help                     this help\n"
  "\n"
  "Each -i's list index is its own position on the command line.\n"
  "any URL takes ?filter=<pids> to drop PIDs, e.g. ?filter=101,0x20.\n\n"
  "/export/<fmt>/<type> (type: m3u|xspf) lists every channel as one\n"
  "playlist. ?host=, ?input=1,3,4, ?filter=, ?keep_multicast, ?plain.\n\n"
  "on an MPTS source, hls/hls-fmp4/llhls/dash/lldash demux the first\n"
  "arriving PMT.\n"
  "Use ?pmt=<pid> (dec or 0x-hex) to pick a different one. ts\n"
  "passes the whole MPTS.\n"
  "\n"
  "On a program carrying LCEVC, hls/hls-fmp4/llhls/dash/lldash accept\n"
  "?lcevc=base|full|all|<n>: strip it, keep it (default), list every\n"
  "alternative in the manifest, or pick one by index/PID.\n"
  "disable this feature with --no-lcevc.\n"
  "\n"
  "Examples:\n"
  "  %s -i sds://239.19.75.1:3937\n"
  "  %s -l 0.0.0.0:9080 -i channels.m3u\n"
  "  %s -L [::]:9443 --tls-cert server.crt --tls-key server.key -i ch.xspf\n\n",
  TOOL_NAME, TOOL_NAME, DEFAULT_CONFIG_PATH, TOOL_NAME, TOOL_NAME, TOOL_NAME);
}

