/* Copyright 2026 dvbipitools authors. Licensed under GPL-3.0-or-later.
 * See NOTICE and LICENSE for details and authorship information. */

#include <stdio.h>

#include "priv.h"
#include "../version.h"

void tvh_print_help(void) {
  printf(
  "usage: %s -i <uri> [per-input options] [-i <uri> ...] {-m <mcast>:<port>|-R <uri>} [options]\n\n"
  "a micromuxer and scrambler.\n"
  "It takes one or more TS (multicast, http(s)+ts/hls+ts/hls+fmp4/llhls/dash/lldash, SRT, RIST or stdin)\n"
  "and re-packages them as one transport stream under a new PAT/NIT with a merged EIT and rewritten PMT.\n\n"
  "A single -i: normal SPTS. Multiple -i: MPTS, one program per input.\n\n"
  "options:\n"
  "  -i, --input <uri>              udp://, rtp://, http(s)://, rist://@host:port[?query]\n"
  "                                 (single peer, @ marks it listening, srt://[@]host:port\n"
  "                                 (single peer, or \"-\" for stdin; repeatable.\n"
  "                                 each RIST/SRT input is an extra thread.\n"
  "  -p, --pmt-pid <pid>            -i before: select program by PMT PID\n"
  "                                 (dec or 0x-hex; default: first live one)\n"
  "  -m, --mcast <g>:<p>            output multicast group:port ([addr6]:port for IPv6)\n"
  "  -O, --out-iface <iface>        outgoing multicast interface name\n"
  "  -u, --udp                      plain UDP output (default: RTP-wrapped; -m output only)\n"
  "  -T, --ttl <n>                  multicast TTL / hop limit (default: 1)\n"
  "      --dscp <v>                 output DSCP marking: video-high|video-low|voice|\n"
  "                                 signalling|best-effort|0..63 (default: video-high)\n"
  "      --al-fec <L>:<D>           Annex E Layer 1 FEC (SMPTE 2022-1), L*D<=400, L<=40\n"
  "      --al-fec-port <port>       AL-FEC stream UDP port, requires --al-fec\n"
  "  -R, --remote <uri>             rist://host:port[?query] or srt://host:port output,\n"
  "                                 bonded with any other -R of the same scheme given.\n"
  "                                 one scheme at a time, rist:// and srt:// don't mix\n"
  "      --rist-profile <p>         simple|main; -R rist:// peers only (default: simple)\n"
  "      --rist-secret <psk>        -R rist:// pre-shared key; requires --rist-profile main\n"
  "      --rist-encryption-type <b> AES key size 128|256, requires --rist-profile main\n"
  "      --rist-cname <name>        -R rist:// cname (default: library default)\n"
  "      --rist-buffer <ms>         -R rist:// recovery buffer (default: library default)\n"
  "      --srt-group-mode <m>       broadcast|backup. required to bond >1 -R srt:// peer\n"
  "      --srt-passphrase <pw>      passphrase for every -R srt:// peer, 10..79 chars\n"
  "      --srt-pbkeylen <n>         AES key length for --srt-passphrase: 16|24|32\n"
  "      --srt-streamid <id>        SRTO_STREAMID for every -R srt:// peer\n"
  "      --srt-packetfilter <c>     SRTO_PACKETFILTER for every -R srt:// peer\n"
  "      --srt-latency <ms>         SRTO_LATENCY for every -R srt:// peer\n"
  "  -n, --nit <text|->             NIT (whole output): default passthrough; \"-\" drops\n"
  "      --default-provider <p>     SDT default provider name, if not overridden\n"
  "                                 by --provider at programme level (default: " TOOL_NAME ")\n"
  "  -b, --bitrate <kbps>           target output bitrate across inputs (default: no shaping)\n"
  "  -S, --stuff                    null-packet stuffing up to -b's target (needs -b)\n"
  "  -B, --burst-limit              cap output at -b's target, never above (needs -b)\n"
  "      --pcr-mode <m>             preserve|rebase|regenerate (default: preserve)\n"
  "                                 regenerate needs -b and -S, -B recommended\n"
  "      --pcr-lead-ms <ms>         regenerate: minimum DTS lead over PCR, raised to the\n"
  "                                 source's own lead if plausible (default: 700, 1..1000)\n"
  "  -e, --error <seconds>          on input error, reconnect after N s (default: fail once,\n"
  "                                 always retries when more than one -i is given)\n"
  "  -k, --insecure                 skip TLS verification\n"
  "      --tsid <n>                 transport_stream_id (default 1)\n"
  "      --onid <n>                 original_network_id (default 1)\n"
  "  -v, --verbose                  periodic stats on stderr\n"
  "      --color <when>             auto|always|never (default auto)\n"
  "      --metrics <path>           socket for metrics (default: /run/dvbipitools/metrics.sock)\n"
  "      --metrics-id <name>        stable instance id. metrics are disabled unless set\n"
  "      --metrics-interval <s>     snapshot interval in seconds (default: 5)\n"
  "      --metrics-inspect-ts <lvl> TS health metrics: off|basic|medium|full (default: off)\n"
  "      --metrics-inspect-ts-pids <list> per pid and per service counters (default: none)\n"
  "      --cas-algo <a>             enable CAS: cissa|csa2|csa1 (default: disabled)\n"
  "      --cas-ecmg <ep>            ECMG address, tcp://host:port. repeatable, one CAS vendor\n"
  "                                 per --cas-ecmg (required with --cas-algo)\n"
  "                                 see options scoped to this below.\n"
  "      --cas-pids <list>          PIDs to scramble: comma-separated pids and/or video/audio/lcevc\n"
  "                                 keywords (default: video,audio - lcevc never implied)\n"
  "      --cas-cp-duration <ms>     crypto-period in ms, shared by vendors (default: 10000)\n"
  "      --cas-fallback-clear       on total outage (or a --cas-required vendor down): clear\n"
  "                                 instead of staying scrambled on the last known-good CW\n"
  "      --biss2-sw <hex32>         enable BISS2 Mode 1/E: 32 hex char Session Word, scrambles\n"
  "                                 with CISSA. No ECMG/EMMG. Mutually exclusive with --cas-algo\n"
  "      --biss2-emit-esw <id>      with --biss2-sw: log the AES-128-ECB Encrypted Session Word\n"
  "                                 for this 32 hex char receiver ID, for out-of-band distribution\n"
  "      --biss1-sw <hex12>         enable legacy BISS1 Mode 1: 12 hex char Session Word,\n"
  "                                 scrambles with CSA1. Mutually exclusive with --biss2-sw/--cas-algo\n"
  "      --biss2-ca-receivers <dir> enable BISS2 Mode CA: directory of PEM public keys, one\n"
  "                                 per entitled receiver/group. Rescanned on SIGHUP. Removed = revoked\n"
  "                                 (forces a Session Key change).\n"
  "                                 Mutually exclusive with --biss1-sw/--biss2-sw/--cas-algo\n"
  "      --biss2-ca-session-id <n> administratively unique entitlement_session_id, dec or\n"
  "                                 0x-hex, 16 bit (default: random at startup)\n"
  "  -d, --daemonize                fork to background after startup\n"
  "  -c, --config <path>            YAML config file (default: %s, if present)\n"
  "      --config-strict            fail on config file issues instead of warnings\n"
  "      --configtest               check the config file, then exit\n"
  "  -h, --help                     this help\n\n"
  "scoped to the -i input right before:\n"
  "      --sid <n>                  service_id/program_number (default: auto)\n"
  "  -s, --sdt <text|->             SDT service_name. default=passthrough, \"-\" drops\n"
  "      --provider <text>          SDT service_provider_name.\n"
  "                                 default=passthrough (or --default-provider with -s)\n"
  "  -I, --iface <iface>            incoming multicast interface name\n"
  "      --strip-eit                drop source EIT (default: passed through)\n"
  "      --strip <list>|none        comma list of DATA,ECM to drop (default: none)\n"
  "      --hbbtv <url>              inject an AIT (default: none)\n"
  "      --hbbtv-org-id <n>         HbbTV organisation_id (required with --hbbtv)\n"
  "      --hbbtv-app-id <n>         HbbTV application_id (required with --hbbtv)\n"
  "      --rist-profile-in <p>      simple|main, -i rist:// only (default: simple)\n"
  "      --rist-encryption-type-in <b> AES key size 128|256, input (--rist-profile-in main)\n"
  "      --srt-passphrase-in <p>    passphrase, 10..79 chars.  -i srt:// only\n"
  "      --srt-pbkeylen-in <n>      AES key length 16|24|32, requires --srt-passphrase-in\n"
  "      --srt-streamid-in <id>     SRTO_STREAMID, -i srt:// only\n"
  "      --srt-packetfilter-in <c>  SRTO_PACKETFILTER, -i srt:// only\n"
  "      --srt-latency-in <ms>      SRTO_LATENCY, -i srt:// only\n"
  "      --jitter-ms <ms>           de-jitter buffer, 1..2000 (default: off)\n\n"
  "scoped to --cas-ecmg right before:\n"
  "      --cas-ecmg-version <n>     protocol version 2|3 (default: auto-negotiate)\n"
  "      --cas-super-id <n>         Super_CAS_id, dec or 0x-hex (required per vendor)\n"
  "      --cas-ecm-id <n>           ECM_id (required per vendor)\n"
  "      --cas-ecm-pid <pid>        ECM stream PID (default: 0x0020)\n"
  "      --cas-emmg-port <n>        our EMMG listener port (default: 8002)\n"
  "      --cas-emmg-max-conns <n>   max concurrent EMMG client conns (default: 8, max: 64)\n"
  "      --cas-emmg-version <n>     EMMG protocol version 2|3 (default: client proposal)\n"
  "      --cas-emmg-reverse <ep>    reverse EMMG, dial out to tcp://host:port\n"
  "      --cas-emm-pid <pid>        output PID for its EMM stream (default: 0x0021)\n"
  "      --cas-resilience <r>       ECMG loss handling, frozen|cycling|silent (default: frozen)\n"
  "      --cas-required             its outage forces the global fallback regardless of others\n"
  "      --cas-cwenc-algo <a>       encrypt CWs per Annex D, des56|aes128|aes256 (default: off)\n"
  "      --cas-cwenc-aes-mode <m>   stream|ecb, aes* only (default: stream)\n"
  "      --cas-cwenc-fixed-key <hx> 14/32/64 hex chars for des56/aes128/aes256 (default: Annex D ROM)\n"
  "      --cas-cwenc-key-list-a <p> 2048-byte Annex D key list file\n"
  "      --cas-cwenc-key-list-b <p> same, second list\n\n"

  "examples:\n"
  "  %s -i rtp://@239.19.75.1:8700 -m 239.1.1.1:5000 -s \"My Channel\"\n"
  "  %s -i https://host/live/x/y.ts -m 239.1.1.2:5000 -b 8000 -S -B\n"
  "  %s -i rtp://@239.19.75.1:8700 --sdt \"Channel A\" -i rtp://@239.19.75.2:8700 --sdt \"Channel B\" \\\n"
  "     -m 239.1.1.3:5000 -e 5\n",
  TOOL_NAME, DEFAULT_CONFIG_PATH, TOOL_NAME, TOOL_NAME, TOOL_NAME);
}
