name: Debian package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: amd64
          - arch: armhf
            crosspkg: crossbuild-essential-armhf
          - arch: arm64
            crosspkg: crossbuild-essential-arm64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake debhelper devscripts ${{ matrix.crosspkg }}
    - name: packaging
      run: |
        if [ "${{ matrix.arch }}" = "amd64" ]; then
          dpkg-buildpackage -us -uc -b
        else
          dpkg-buildpackage -us -uc -b -a${{ matrix.arch }} -d
        fi
        mv ../*.deb .
    - uses: actions/upload-artifact@v4
      with:
        name: deb-${{ matrix.arch }}
        path: '*.deb'

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: deb-*
        merge-multiple: true
        path: dist
    - name: assets
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.deb
